### ISSUE TITLE
On dismissed?

### ISSUE THREAD

**Issue by xbroak** [KeepSafe/TapTargetView#1]
This might already be solved, but i'd like to do the following: Get notified when the user taps outside of the info window thus it being "cancelled". The reason for that is i'd like to do the exact same thing in the demo, but without needing to write in each of the descriptions "To close this, tap on the highlighted item" or similar. To us it may be obvious but it'd be great if simply tapping anywhere allowed me to display the next info item.

**Comment by xiphirx** [comment]
Thanks for reporting. This is actually not supported as of now, but definitely should be. 

I imagine appending `onCancel` to the listener interface would suffice. Does that sound good to you?

**Comment by xbroak** [comment]
That'd be perfect i'd say! :+1: 

An aside, everything is working just beautifully!

**Comment by xiphirx** [comment]
Cool. I can fix this in a few hours. Feel free to submit a PR in the meantime if you need it sooner

**Comment by xbroak** [comment]
No problem, no rush required!

------ Original Message ------
