### ISSUE TITLE
Listener discrepancy.

### ISSUE THREAD

**Issue by lyrafelipe** [KeepSafe/TapTargetView#10]
I added the library as a dependency in my project and started following the sample App you provided to create a "Helper" for my users.

When I added the listener, so I could make a sequence of "tap targets", I noticed there was a discrepancy between the listener provided by the imported library and the sample.

The listener provided by the library looks like this:
```
    public interface Listener {
        void onTargetClick(TapTargetView view);
        void onTargetLongClick(TapTargetView view);
    }
```

The listener used in the sample looks like this:
```
    public static class Listener {
        public void onTargetClick(TapTargetView view) {
            view.dismiss(true);
        }

        public void onTargetLongClick(TapTargetView view) {
            view.dismiss(true);
        }

        public void onTargetCancel(TapTargetView view) {
            view.dismiss(false);
        }
    }
```

Could you please take a look?

**Comment by leisim** [comment]
The `onTargetCancel` method was added recently and is not part of the last release yet. 
You have to wait for the next release or include the source ;)

**Comment by xiphirx** [comment]
Please wait for the next version to use `onTargetCancel`. I'll look into doing snapshot releases so it's possible to use the latest code without including the source.
