### ISSUE TITLE
Add listener for TapTarget inside TapTargetSequence

### ISSUE THREAD

**Issue by prokash-sarkar** [KeepSafe/TapTargetView#101]
Please add listeners for individual targets inside a TapTargetSequence.

**Comment by xiphirx** [comment]
To be clear, are you asking for something along the lines of `TapTargetSequence.Listener.onSequenceStep(TapTarget target)` ?

**Comment by prokash-sarkar** [comment]
Yes. Exactly what I'm looking for.

**Comment by xiphirx** [comment]
@prokash-sarkar take a look at https://github.com/KeepSafe/TapTargetView/pull/102/files and let me know if this will suffice.

**Comment by prokash-sarkar** [comment]
Tested & working as expected. Thanks for the support.
