### ISSUE TITLE
tintTarget not working

### ISSUE THREAD

**Issue by lenoch0d** [KeepSafe/TapTargetView#104]
- [x] I have verified the issue exists on the latest version
- [x] I am able to reproduce it

**Version used:** 1.6.1
**Support Library version:** 25.1.0
**Android version:** 6.0

Hello. After updating library from 1.6.0 to 1.6.1, the tintTarget method doesn't work for me anymore. The same code worked well with version 1.6.0. I'm using it in a sequence to tint a toolbar menu item's icon. 

My icon in toolbar is white and should be tinted to yellow, which is my primaryColor. But the icon stays white so it's not visible.
 ```
TapTargetSequence sequence = new TapTargetSequence(getActivity()) .targets(
// another TapTargets.. 
       TapTarget.forToolbarMenuItem(toolbar, R.id.action_one, getString(R.string.guide_title), getString(R.string.guide_subtitle))
                                .cancelable(false)
                                .tintTarget(true))
 .listener(new TapTargetSequence.Listener() {

                    @Override
                    public void onSequenceFinish() {    }

                    @Override
                    public void onSequenceCanceled(TapTarget lastTarget) {       }
                });

```

**Comment by xiphirx** [comment]
The only thing that could modify the behavior of `tintTarget` that is new in 1.6.1 would be the fact that I'm no longer creating bitmaps for targets that are 0x0 big, however from your code it seems like the problem `TapTarget` is not the first target displayed, so there shouldn't be any race conditions causing your view to be 0x0 in size.

I will have to see if I can reproduce this on my end...

**Comment by lenoch0d** [comment]
Yes, it's not the first target in the sequence (there are 4 more TapTarget.forView() before), but is's the first ToolbarMenuItem target. And there are no other targets after.

I also forgot to mention that when I exit my app using the home button right in the step, when the icon  should be tinted (but is not), and then open the app again, the icon **is** tinted properly.

**Comment by xiphirx** [comment]
Actually its reproducible by running the sample... Looking into it. Thanks for the report

**Comment by xiphirx** [comment]
Hi @lenoch0d I believe I have fixed it. Can you please try the latest snapshot and let me know?

**Comment by lenoch0d** [comment]
@xiphirx I've tried it and it works!. Thank you for fixing it and for the library!
