### ISSUE TITLE
Title and description text goes out of the screen 

### ISSUE THREAD

**Issue by afif1991** [KeepSafe/TapTargetView#106]
on small screen it works perfectly but for bigger screen (5' and above ) text hides in bottom. 

![screenshot_2017-01-13-12-11-42-649_com bluemark ablifree](https://cloud.githubusercontent.com/assets/23213966/21920894/0f4092a4-d98a-11e6-880d-2282e85a21f9.png)

**Comment by xiphirx** [comment]
What version of the library are you using?

**Comment by afif1991** [comment]
Android 6.0 ... and 
com.getkeepsafe.taptargetview:taptargetview:1.6.0

**Comment by xiphirx** [comment]
How much text are you trying to display? Can you share the code you're using to show the TapTargetView ?

**Comment by afif1991** [comment]
This is the sequence and this happens only for the first TapTarget.

{
            TapTargetSequence sequence = new TapTargetSequence(getActivity());
            sequence.targets(TapTarget.forView(mShareLocationSwitch, getString(R.string.home_info_text), getString(R.string.share_info_message)).targetRadius(90).targetCircleColor(R.color.white).dimColorInt(getResources().getColor(R.color.black)),
                    TapTarget.forView(mFetchCardsSwitch, getString(R.string.home_info_text), getString(R.string.fetch_info_text)).targetRadius(90).targetCircleColor(R.color.white).dimColorInt(getResources().getColor(R.color.black)),
                    //TapTarget.forToolbarMenuItem(((HomeActivity)getActivity()).getToolBar(),R.id.filter_menu ,getString(R.string.home_info_text), getString(R.string.filter_info_message)).targetCircleColor(R.color.black),
                    TapTarget.forView(((HomeActivity) getActivity()).getSavedCardView(), getString(R.string.saved_cards_text), getString(R.string.saved_cards_info_message)).targetCircleColor(R.color.white).dimColorInt(getResources().getColor(R.color.black)),
                    TapTarget.forView(((HomeActivity) getActivity()).getAddCardView(), getString(R.string.home_info_text), getString(R.string.add_card_info_message)).targetCircleColor(R.color.white).dimColorInt(getResources().getColor(R.color.black)),
                    TapTarget.forView(((HomeActivity) getActivity()).getProfileView(), getString(R.string.profile_title_text), getString(R.string.profile_info_message)).targetCircleColor(R.color.white).dimColorInt(getResources().getColor(R.color.black)))
                    .listener(new TapTargetSequence.Listener() {
                        @Override
                        public void onSequenceFinish() {
                            mAppsPreferences.setIsShowcaseViewShown(true);
                            ((HomeActivity) getActivity()).showFilterInfoView();
                        }

                        @Override
                        public void onSequenceCanceled(TapTarget lastTarget) {
                            mAppsPreferences.setIsShowcaseViewShown(true);
                        }
                    });
            sequence.start();
        }

title Text : Near-by profile
Description text : Share your profile in your location.

**Comment by xiphirx** [comment]
Hmm, I can't seem to replicate the behavior on my end. Can you pull out that `TapTarget` and show it by itself and enable debug drawing via `TapTargetView#setDebugDraw(true)` ?

Also if possible, can you give the screen dimensions and the bounds rect of the view you're targeting?

**Comment by xiphirx** [comment]
@afif1991  I have just landed #109 which will allow me to see what is going wrong. Can you please run a snapshot build of the library and post the debug information that appears? You can enable debug drawing via `TapTargetView#setDebugDraw(true)`

**Comment by xiphirx** [comment]
@afif1991 any updates?

**Comment by xiphirx** [comment]
Closing due to lack of information. Please re-open with the requested information.
