### ISSUE TITLE
Any callback on onOuterCircleClick incase of TapTargetSequence

### ISSUE THREAD

**Issue by Khareesh0892** [KeepSafe/TapTargetView#112]
Am trying to continue sequence when user tries to tap on outer circle.
But while using 'sequence.continueOnCancel(true)', its working for back press & dimColor color clicks but not 'onOuterCircleClick'. Can anyone help me ?

**Comment by xiphirx** [comment]
Currently it doesn't seem like you can do this. Tapping on the outer circle is not very well defined at the moment so I'll have to think about how best to support this sort of customization. In the meantime, you can create your own version of TapTargetSequence to handle this for you.
