### ISSUE TITLE
Decrease minsdk

### ISSUE THREAD

**Issue by KashifAnwaar** [KeepSafe/TapTargetView#113]
Hi there!
Can you please decrease the minsdk from 14 to 9 or most least version to support more android devices. if so please do it.
I guess you can because [MaterialTapTarget ](https://github.com/sjwall/MaterialTapTargetPrompt) a similar library has minsdk to 9.

Thank you.

**Comment by xiphirx** [comment]
The library uses things that are not available on API 9 and I do not think it's worth adding in something like nine old androids just to support 1% of devices. I also do not have devices that old to test with

**Comment by KashifAnwaar** [comment]
ok but 1% in terms android users is not less. 1% = several thousands of devices.
