### ISSUE TITLE
Focus on multiple views

### ISSUE THREAD

**Issue by MehdiChouag** [KeepSafe/TapTargetView#115]
I recently started to integrate this library in one of my projects. I facing a situation where I'd like to show a tap target on multiple views.

I have two solution: 
1. Wrap my views with a ViewGroup and use it to display the tap target
2. Get the `Rect` of each view and compute them so all my views are contain in a `Rect`.

I don't like the first solution because I'll have to add a useless ViewGroup in my hierarchy, the second one is better in term of performance but I think it could handle internally in the library.

Is it possible to add a method to show a tap target on multiple views like this `TapTarget.forViews(CharSequence title, CharSequence description, View... views)`

(BTW Thanks guys for awesome library)

**Comment by xiphirx** [comment]
I feel like this is outside of the scope of the library and the UX pattern. Tap targets are to isolate a _single_ view rather than multiple. I would personally go with the bounds calculation solution.
