### ISSUE TITLE
TapTarget is placed behind RecyclerView items.

### ISSUE THREAD

**Issue by sandro-csimas** [KeepSafe/TapTargetView#120]
I'm trying to add a TapTarget in a RecyclerView item, but the TapTarget appears behind the item.
````
// Gets the first RecyclerView item
View view = UIUtils.getFirstVisibleItem(circlesView);
TapTarget tapTarget = TapTarget.forView(view, title, description);
new TapTargetSequence(activity).targets(tapTarget).start();
````
````
public class UIUtils {
  public static View getFirstVisibleItem(RecyclerView recyclerView) {
    View view = null;
    RecyclerView.LayoutManager layoutManager = recyclerView.getLayoutManager();
    if(layoutManager instanceof LinearLayoutManager) {
      int index = ((LinearLayoutManager) layoutManager).findFirstCompletelyVisibleItemPosition();
      view = layoutManager.findViewByPosition(index);
    }
    return view;
  }
}
````
If I increase the target radius, the appearance is a little better, but is not working as I expected. Look at the second screenshot.

- [X] I have verified the issue exists on the latest version
- [X] I am able to reproduce it

**Version used:**
com.getkeepsafe.taptargetview:taptargetview:1.7.0

**Stack trace:**
No stack trace

**Android version:**
6.0

**Screenshots:**
![screenshot from 2017-01-31 18 39 58](https://cloud.githubusercontent.com/assets/1282074/22485517/bd5c6af8-e7e4-11e6-89b7-978499a3a16c.png)![screenshot from 2017-01-31 18 41 28](https://cloud.githubusercontent.com/assets/1282074/22485601/0835dd8e-e7e5-11e6-8570-768958618fa0.png)

**Comment by xiphirx** [comment]
Interesting... are you setting the elevation for the view that appears on top?

A view hierarchy dump of that screen would be helpful in figuring out whats going on if youre not setting the elevation.

**Comment by sandro-csimas** [comment]
No, I'm not setting elevation.
This is a simplified version of my layout:
````
<?xml version="1.0" encoding="utf-8"?>
<android.support.v4.widget.DrawerLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/drawer_layout"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <RelativeLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <include layout="@layout/progress_view"/>

        <LinearLayout
            android:orientation="vertical"
            android:layout_width="match_parent"
            android:layout_height="match_parent">

            <include layout="@layout/toolbar"/>

            <LinearLayout
                android:id="@+id/circles_layout"
                android:orientation="vertical"
                android:visibility="gone"
                android:layout_width="match_parent"
                android:layout_height="match_parent">

                <android.support.v4.widget.SwipeRefreshLayout
                    android:id="@+id/refresh_layout"
                    android:layout_width="match_parent"
                    android:layout_height="match_parent">

                    <android.support.v7.widget.RecyclerView
                        android:id="@+id/circles"
                        android:layout_width="match_parent"
                        android:layout_height="match_parent"
                        android:clipToPadding="false"/>

                </android.support.v4.widget.SwipeRefreshLayout>

            </LinearLayout>

        </LinearLayout>

        <android.support.design.widget.CoordinatorLayout
            android:id="@+id/coordinator_layout"
            android:layout_width="match_parent"
            android:layout_height="match_parent">

            <android.support.design.widget.FloatingActionButton
                android:id="@+id/new_circle"
                android:visibility="gone"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_gravity="bottom|end"
                android:layout_margin="@dimen/fab_margin"
                android:src="@drawable/add_circle"
                app:backgroundTint="@color/accent"
                app:rippleColor="@color/accent_dark"
                app:borderWidth="0dp"
                app:elevation="6dp"/>

        </android.support.design.widget.CoordinatorLayout>

    </RelativeLayout>

    <android.support.design.widget.NavigationView
        android:id="@+id/navigation_view"
        android:layout_width="wrap_content"
        android:layout_height="match_parent"
        android:layout_gravity="start"
        app:itemTextAppearance="@style/NavigationViewItemTextAppearance"
        app:menu="@menu/menu_drawer"/>

</android.support.v4.widget.DrawerLayout>
````

**Comment by sandro-csimas** [comment]
This is happening in other two RecyclerViews of other two fragments (ViewPager).

**Comment by xiphirx** [comment]
Hi, the problem here is that youre targeting the entire item view, which is quite large. I suspect you want to target part of the item view, and so you will need to target the specific view instead of the entire item view. Another option is specifying bounds to target.

The reason why it appears that the TapTargetView is behind is because we re-draw your target view on top of the tap target (otherwise you wouldnt be able to see it). Since your view is extra large, it is extending beyond the bounds of the target circle.

Tap targets are meant for smaller type views, like FABs or icon buttons, not entire RecyclerView items.

I'm curious to know what you were expecting to have happen when targeting the item view, though. It might be worth adding a convenience function where you can specify the view and then some `Rect` that is within the view's bounds to target.

**Comment by sandro-csimas** [comment]
I was expecting the inner circle to appear above the view, in the middle of it. I'm using another library that works fine. I will try to create a Rect, but I think it will be nice if the library support. What do you think?
![screenshot from 2017-02-04 21 15 57](https://cloud.githubusercontent.com/assets/1282074/22622659/2d8df07a-eb1f-11e6-8a96-46faf19b9a28.png)

**Comment by xiphirx** [comment]
You can accomplish it by using `forBounds` and specifying a `Rect` that is within the view's bounds.

**Comment by sandro-csimas** [comment]
@xiphirx. Specifying a Rect is not working well.
Look at the follow screenshots. I draw a Rect in Canvas and I pass the same Rect to TapTarget. Any suggestion?
````
int centreX = (int) (view.getX() + view.getWidth() / 2);
int centreY = (int) (view.getY() + view.getHeight() / 2);
Rect bounds = new Rect(centreX - 100, centreY + 100, centreX + 100, centreY - 100);

Paint paint = new Paint();
paint.setColor(Color.rgb(255, 0, 0));
paint.setStyle(Paint.Style.FILL);
Bitmap bitmap = Bitmap.createBitmap(view.getWidth(), view.getHeight(), Bitmap.Config.ARGB_8888);
Canvas canvas = new Canvas(bitmap);
canvas.drawRect(bounds, paint);
view.setBackgroundDrawable(new BitmapDrawable(bitmap));

TapTarget tapTarget = TapTarget.forBounds(bounds, title, description);
````
![screenshot from 2017-02-05 01 02 44](https://cloud.githubusercontent.com/assets/1282074/22623594/30ab1416-eb3f-11e6-85f6-653ddc03b961.png)
![screenshot from 2017-02-05 01 02 22](https://cloud.githubusercontent.com/assets/1282074/22623595/30d5fbb8-eb3f-11e6-9728-0b04cdd1e19b.png)

**Comment by xiphirx** [comment]
You want to use something like 
```java
final int[] location = new int[2];
view.getLocationOnScreen(location);
new Rect(location[0], location[1], location[0] + view.getWidth(), location[1] + view.getHeight());
```

instead of `getX` and `getY` since those methods are relative to the parent, not the screen.
