### ISSUE TITLE
white color doesn't work with dark theme.

### ISSUE THREAD

**Issue by goelswati** [KeepSafe/TapTargetView#123]
- [✓] I have verified the issue exists on the latest version
- [✓] I am able to reproduce it

**Version used:**
1.7.0

**Android version:**
All

If app needs white color for target circle and title/description, but the theme is "dark", then it is not achievable since as per the 'TapTargetView' source code,

```
        final int targetCircleColor = target.targetCircleColorInt(context);
        if (targetCircleColor != UNSET_COLOR) {
            targetCirclePaint.setColor(targetCircleColor);
        } else {
            targetCirclePaint.setColor(isDark ? Color.BLACK : Color.WHITE);
        }
```

Because from [Color - Android Source Code](http://grepcode.com/file/repo1.maven.org/maven2/org.robolectric/android-all/4.4_r1-robolectric-1/android/graphics/Color.java) the value of white color value is "-1" in .class file. Which makes the above condition false since value of "UNSET_COLOR" is also -1.

**Comment by xiphirx** [comment]
Thanks for the report. The library should use something like Integer.MIN_VALUE instead, I'll fix it tomorrow
