### ISSUE TITLE
Outer circle in tablet layouts gets too big

### ISSUE THREAD

**Issue by pedrodanielcsantos** [KeepSafe/TapTargetView#124]
The outer circle, when in tablet layouts is extremely wide, when applying the TapTargetView to a FAB button on the top right corner of the screen. Maybe there could be a parameter to set the maximum radius of the outer circle in the `TapTargetView` builder.

- [x] I have verified the issue exists on the latest version
- [x] I am able to reproduce it

**Version used:**
`1.7.0`

**Stack trace:**
Stack trace not applicable. 

Here's a print screen of a tablet in landscape mode:
![device-2017-02-01-185209](https://cloud.githubusercontent.com/assets/8170256/22521317/92b954a2-e8af-11e6-9e38-7d5b285178f3.png)

**Android version:**
Nougat (`7.1.1`).

**Comment by xiphirx** [comment]
lol that is a bug :) It seems like the library is lacking tablet support at the moment... Will add soon. Thanks for the report!

**Comment by pedrodanielcsantos** [comment]
No worries, and thanks for the fast reply @xiphirx  😄 Can you please give me any prediction for a release with this fix ?

**Comment by xiphirx** [comment]
It should be within a week. Fixing this should be pretty simple, The library needs to detect tablet sized screens and adjust the text layout bounds accordingly. IIRC the design guidelines specify that phone sized screens will use the full screen width for the text bounds while tablets will use a fixed, smaller size.

A PR would be great if you're up for it!

**Comment by pedrodanielcsantos** [comment]
My plate is a bit full at the moment 😞 I'm not sure when I'd have time to pick it up properly in the next couple of weeks. Still, if I have some time, I'll let you know.

**Comment by xiphirx** [comment]
Please try out a snapshot and let me know what you think!

**Comment by pedrodanielcsantos** [comment]
Hi @xiphirx ! Thanks for the fix, it's much nicer now 👏 Still, I'd leave a suggestion: As the guidelines (at least from what I've seen) don't specify the max width for tablets (only say that for smaller screens, the outer circle should extend beyond the surface's edges - which is very nicely done now), you could make the value of `TEXT_MAX_WIDTH` parameterizable via the `TapTarget` object, for instance, as the current value seems a bit narrow on some situations (some tablet sizes, title/subtitle length, etc). What do you think ?

**Comment by xiphirx** [comment]
The value comes from the screenshots, they all have that width specified for the text layouts, it doesn't seem like there are clear guidelines though. I feel like another issue needs to be opened for more tablet support since the library is also missing the whole ”clip to the surface bounds” part of tablet support. #128
