### ISSUE TITLE
TapTargetView is rendered behind custom view

### ISSUE THREAD

**Issue by pflammertsma** [KeepSafe/TapTargetView#126]
**Version used: 1.7.0**

**Stack trace: N/A**

**Android version: 6.0.1 and 4.4.0**

I've applied a TapTargetView onmy my custom view for Cryptogram, but noticed that the rendering of text appeared on top of it. This is the code I'm working with:

    TapTargetView.showFor(
            CryptogramActivity.this,
            TapTarget.forView(mCryptogramView,
                    "Hyphenation",
                    "Watch out, this is a hyphen! The word continues on the next line.")
                     .titleTextColor(R.color.white)
                     .descriptionTextColor(R.color.white)
                     .tintTarget(false)
                     .transparentTarget(false),
            new TapTargetView.Listener() {
                @Override
                public void onTargetClick(TapTargetView view) {
                    PrefsUtils.setHighlightedHyphenation(true);
                }
            });

Which yields:

![image](https://cloud.githubusercontent.com/assets/286051/22604311/3bf66cac-ea4b-11e6-96c7-6c344205070d.png)

I had expected the overlay to appear on top of my custom view, as it appears to for the Toolbar and the rest of my activity.

**Comment by xiphirx** [comment]
Interesting... Are you setting the elevation on your own view? Can you share details / code about your view? Are you adding your view programmatically?

**Comment by pflammertsma** [comment]
No, there are no elevations set. Furthermore, the problem exists on pre-Lollipop devices.

The custom view is included in the layout, no frills there. It's a fairly simple extension of TextView that draws puzzle characters on a canvas. The problematic commit can be found here:

https://github.com/pflammertsma/cryptogram/tree/3524420f29ee7891c6dfe6ccf365574dcfbb8a9b

**Comment by pflammertsma** [comment]
I should point out that the issue no longer occurs when using `TapTarget.forBounds()`; it only applies to `TapTarget.forView()` on the view in question.

**Comment by xiphirx** [comment]
Interesting! Thanks. It's great that the app is open source, I'll take a look tonight!

**Comment by pflammertsma** [comment]
Ultimately the issue doesn't affect me as per chance `TapTarget.forBounds()` was what I needed, but it certainly is an interesting bug!

**Comment by xiphirx** [comment]
I see what the problem is: You're targeting a very large view (the entire cryptogram), and so, it is re-drawing your targeted view (otherwise it would be obscured), and since its large, it goes outside the bounds of the target circle.

So this seems to be the case of using the wrong target type. You do want to use specific bounds as you already figured out. Targeting a view is for smaller types of views, like FABs.

**Comment by pflammertsma** [comment]
Gotcha. Perhaps a utility method that allows specifying a boundary or
offset within a view would make it easier for applications like this, but
I'm perfectly happy with the solution in place now. Thanks again!
