### ISSUE TITLE
Finalize tablet support

### ISSUE THREAD

**Issue by xiphirx** [KeepSafe/TapTargetView#128]
Continuing on from #124 , we need to also support surface tap target behavior for tablets

**Comment by julioz** [comment]
@xiphirx Any news on this one? Would be great to have 1.9.0 with the latest changes this week.

**Comment by xiphirx** [comment]
Do you need the "clip to surface" behavior in 1.9.0 or do you just need whatever is there released?

**Comment by julioz** [comment]
The current `master` branch. I don't want to use a `SNAPSHOT` though, so a stable version would be the best. Do you have any "defined flow" for releasing the library? How do you determine what goes into each release? And at which point you consider a "closed batch of changes" to be released?

**Comment by xiphirx** [comment]
Unfortunately there isn't a "defined flow" in place right now. It has historically been based on demand (like as you are doing now) and or things that need to be fixed ASAP. I try to keep to the milestone model in place by GitHub, however that doesn't always work in light of public demand for a new release. I fully understand the desire to use a stable release rather than `SNAPSHOT`.

To that end, I can package up 1.9.0 today.

**Comment by xiphirx** [comment]
@julioz Released

**Comment by julioz** [comment]
@xiphirx Thanks, I'll upgrade the lib on my end to use 1.9.0.

I understand how complicated it might be to maintain the library. Eventually the library should aim to fully fulfill the Material Design guidelines for this component, though. Maybe we can define a roadmap based on that? I believe bugfixes will always be present anyway, so this milestone mechanism has worked fine up to this point.

**Comment by xiphirx** [comment]
This _should_ actually be the last thing to fully implement the design specs (unless those specs change), AFAIK. So a roadmap seems a bit unnecessary at this point. 

I'd like to think about how a v2 would work since v1 has some sore spots in its API that came from writing the initial version of this library in a time crunch :) Thats where I think a roadmap of sorts would be beneficial.

**Comment by xiphirx** [comment]
tracking in #227
