### ISSUE TITLE
Layer type hardware causing text rendering problems on 4.4 when TapTargetView is over WebView

### ISSUE THREAD

**Issue by Daio-io** [KeepSafe/TapTargetView#136]
- [x] I have verified the issue exists on the latest version
- [x] I am able to reproduce it

**Version used:**
1.8.0

**Android version:**
4.4.4

When using the TapTargetView on Android 4.4 with a WebView the text will render incorrectly. I noticed in the source code you set layer type to hardware for SDK 18 and above. If the layer type is changed to software this will fix the issue. You may decide this is not enough of a problem and it can be fixed with the solution I have put in my sample app, but I thought I would make you aware.

Created a sample app here to demonstrate the issue
https://github.com/Daio-io/TapTargetView_Bug/tree/master/app/src/main/java/io/daio/taptargetviewbug

Image of problem:
https://github.com/Daio-io/TapTargetView_Bug/blob/master/layer_bug.png

**Comment by xiphirx** [comment]
Hmm that is interesting! I'm curious to know if this problem is isolated to TapTargetView or if it is a problem, with say TextView, in the same scenario.

I'll have to look into this / think about it for a bit before I decide what needs/doesnt need to be done.

Thanks for the interesting report nonetheless!

**Comment by xiphirx** [comment]
I can't seem to replicate this issue on my end, perhaps its a faulty GPU?
![image](https://cloud.githubusercontent.com/assets/993832/23290961/b0f0b260-fa09-11e6-8b52-66a36787c075.png)

Either way, there isnt a good way for the library to detect this case and apply a different layer type, so unfortunately the best thing you can do is what you already figured out: set the layer type to software.

Thanks for bringing it up though!
