### ISSUE TITLE
Error in production (noticed on Pre-Launch Report)

### ISSUE THREAD

**Issue by conzorz** [KeepSafe/TapTargetView#139]
- [x] I have verified the issue exists on the latest version
- [x] I am able to reproduce it:
Has happened on 7 consecutive Pre-Launch Reports.

**Version used: 1.8.0**

**Stack trace:
java.lang.NullPointerException: Attempt to read from field 'java.lang.String android.accounts.Account.type' on a null object reference
**

**Android version: (Samsung) 5.1**

Crashlytics is identifying it as coming from this library but not sure?

Can get more from the logcat if needed but it's a nullPointerException.

**Comment by xiphirx** [comment]
The library does not use anything from `android.accounts`. Please ensure that you are not retrieving a value from a class in that package that is causing the NPE instead.

**Comment by conzorz** [comment]
Ah, thanks. It seems it was a bug on the Pre-Launch device actually.
