### ISSUE TITLE
Check before showing

### ISSUE THREAD

**Issue by kdani41** [KeepSafe/TapTargetView#144]
Is there any way to check if the view is already shown before actually launching the TapTargetView??

so something like 

    if(tapTargetViewIsNotShown) {
        // show the tap target view
    }

I guess this is also a possible solution for #143

**Comment by xiphirx** [comment]
Yes, check `tapTargetView.isVisible()`

**Comment by kdani41** [comment]
Sorry, dumb question got confused with something. Thanks for your library 👍  :)
