### ISSUE TITLE
not overlaying the targeted button

### ISSUE THREAD

**Issue by sebastiansharun** [KeepSafe/TapTargetView#145]
- [x] I have verified the issue exists on the latest version
- [ ] I am able to reproduce it

**Version used:1.8.0**

**Stack trace:**

**Android version:6.0**

![capture](https://cloud.githubusercontent.com/assets/25167111/23793791/fc7c3ed4-05b2-11e7-93db-009ad0c1c991.JPG)

tried code...

       new TapTargetSequence(this)
                .targets(
                        TapTarget.forView(findViewById(R.id.button), "Button 1", "This is button 1 click").tintTarget(false).targetRadius(100).transparentTarget(false),
                        TapTarget.forView(findViewById(R.id.button2), "Button 2", "This is button 2 click").tintTarget(false),
                        TapTarget.forView(findViewById(R.id.button3), "buttton 3", "This is button 3 click").tintTarget(false))

                .start();

**Comment by xiphirx** [comment]
Tap targets are usually for icon sized things. If you want to have your button appear under the tap target, you will need to increase the target radius like you have already and you will need to set `transparentTarget` to true.
