### ISSUE TITLE
java.lang.IllegalArgumentException: Layout: -230 < 0

### ISSUE THREAD

**Issue by avtarsingh1122** [KeepSafe/TapTargetView#146]
the tap target view is not running inside fragments . in devices with api level 23 vr 6.0.1 (OxygenOS version 3.5.6)
showing the above issues
java.lang.IllegalArgumentException: Layout: -230 < 0

As i call the tragetsequence.start() the code crashes ! 

<?xml version="1.0" encoding="utf-8"?>
<android.support.v4.widget.SwipeRefreshLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/refreshStories"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <ListView
        android:id="@+id/listview_stories"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:divider="@null"
        />
    </android.support.v4.widget.SwipeRefreshLayout>

**Inside fragment **

  header = (ViewGroup) inflater.inflate(R.layout.layout_home_header, lvStories, false);
        lvStories.addHeaderView(header);

####################################################################
**the view am passing is the header** 

  public void showTapTour(View view) {
          TapTargetSequence t = new TapTargetSequence(getActivity())
                    .targets(
                            TapTarget.forView(view.findViewById(R.id.button_search), "Tap and make a search on go!","Surf through thousands of smartphones and know everything from stories, to reviews and videos.")
                                    .cancelable(false)
                                    .drawShadow(true)
                                    .tintTarget(false),
                            TapTarget.forView(view.findViewById(R.id.button_compare), "Comparing smartphones now made easy", "Compare any two smartphones head to head and then decide for yourself with the help of a very simplified layout")
                                    .cancelable(false)
                                    .drawShadow(true)
                                    .tintTarget(false)
                    )
                    .listener(new TapTargetSequence.Listener() {

                        @Override
                        public void onSequenceFinish() {
                           
                            selectCountry();

                        }

                        @Override
                        public void onSequenceStep(TapTarget lastTarget) {

                        }

                        @Override
                        public void onSequenceCanceled(TapTarget lastTarget) {
                            // Boo
                        }
                    });

        try{
        t.start();
        } catch (Exception e ){
            e.printStackTrace();
        }
    }

**Comment by peter1408** [comment]
compile 'com.github.KeepSafe:TapTargetView:-SNAPSHOT'
 really really really really saved my ass ! you are genius !
