### ISSUE TITLE
Toolbar icons disappear

### ISSUE THREAD

**Issue by EuMenezes** [KeepSafe/TapTargetView#148]
- [x] I have verified the issue exists on the latest version
- [x] I am able to reproduce it

Version used: 1.8.0
Android version: 6.0.1

I use "TapTargetSequence" with 2 "TapTarget.forBounds", in this 2 i have the same icon of my toolbar.
When the TapTarget finish or is canceled my toolbar icons disappear

Code:
`    private void firstTime() {

        Display display = getActivity().getWindowManager().getDefaultDisplay();
        Point size = new Point();
        display.getSize(size);
        Rect rectInfo = new Rect((size.x - 100), 0, (size.x - 50), (size.y / 6));
        Rect rectUpdate = new Rect((size.x - 200), 0, (size.x - 150), (size.y / 6));

        new TapTargetSequence(getActivity())
                .targets(
                        TapTarget.forBounds(
                                rectInfo, "Legenda", "Identifica as cores dos materiais")
                                .outerCircleColor(R.color.azul)
                                .targetCircleColor(R.color.branco)
                                .titleTextSize(30)
                                .descriptionTextSize(15)
                                .textColor(R.color.preto)
                                .textTypeface(Typeface.SANS_SERIF)
                                .drawShadow(true)
                                .cancelable(false)
                                .tintTarget(false)
                                .transparentTarget(false)
                                .icon(getResources().getDrawable(R.drawable.ic_help_outline_black_24dp))
                                .targetRadius(60).id(1),

                        TapTarget.forBounds(
                                rectUpdate, "Recarregar", "Refazer Validação de Materiais")
                                .outerCircleColor(R.color.azul)
                                .targetCircleColor(R.color.branco)
                                .titleTextSize(30)
                                .descriptionTextSize(15)
                                .textColor(R.color.preto)
                                .textTypeface(Typeface.SANS_SERIF)
                                .drawShadow(true)
                                .cancelable(false)
                                .tintTarget(false)
                                .transparentTarget(false)
                                .icon(getResources().getDrawable(R.drawable.reload))
                                .targetRadius(60).id(2)
                ).start();
    }`

Screen after "TapTargetSequence" appear:
![image](https://cloud.githubusercontent.com/assets/7975434/24043434/4a8e6178-0af5-11e7-9100-f1aac16ba693.png)

Screen without "TapTargetSequence" appear:
![image](https://cloud.githubusercontent.com/assets/7975434/24043500/aadf34e4-0af5-11e7-984d-c228c5fdf1d9.png)

What wrong did i do?

**Comment by xiphirx** [comment]
How are you adding those buttons to your toolbar? Dump the layout hierarchy, are they still there?

**Comment by EuMenezes** [comment]
The buttons still there, you can touch and interacts with they, but the image disappear.
The buttons are in a xml that i inflate in "onCreateOptionsMenu" method.

**Comment by xiphirx** [comment]
I tried replicating your code, however I am not able to replicate the issue... 

Did you try using `TapTarget.forToolbarMenuItem(...)` ?

If not, can you provide a layout + code that reproduces the issue?

**Comment by EuMenezes** [comment]
May i send you an email with the requested?
I prefer send you an email than write here

**Comment by xiphirx** [comment]
Sure you can email me via my github username at Gmail

**Comment by xiphirx** [comment]
Closing, please open another issue if you have more information.

**Comment by Rainer-Lang** [comment]
I have the same problem.
I create the menu via xml.

**Comment by Rainer-Lang** [comment]
I "was" using:
```icon(...)```
```transparentTarget(false)```

Changed it to:
NO ```icon(...)``` and ```transparentTarget(true)``` -> and now it's working.

I think it's the ```transparentTarget(false)```

**Comment by Rainer-Lang** [comment]
@xiphirx Could you have a look here? Thanks.
