### ISSUE TITLE
[Enhancement] Cancle also on outercircle-click

### ISSUE THREAD

**Issue by matecode** [KeepSafe/TapTargetView#149]
It would be great to also have the option to get a cancel or maybe an extra event on a click on the outer circle.

**Comment by julioz** [comment]
You can use `TapTargetView:: onOuterCircleClick` for it.

**Comment by matecode** [comment]
Ah ok i see ... also found "considerOuterCircleCanceled"

So I close this issue, thanks. But consider to update/complete the docs 👍
