### ISSUE TITLE
drawShadow and transparentTarget not working well together

### ISSUE THREAD

**Issue by matecode** [KeepSafe/TapTargetView#150]
- [ X] I have verified the issue exists on the latest version
- [ X] I am able to reproduce it

**Version used:1.8.0**

**Android version: all**

If you use `.drawShadow(true)` and `.transparentTarget(true)` together, the target is dimmed from the shadow

**Comment by xiphirx** [comment]
Thanks for the report! Will look into it soon

**Comment by xiphirx** [comment]
Unfortunately this seems like a limitation of utilizing a `ViewOutlineProvider`, since it must outline a convex shape...

There's not much I can do unfortunately. Utilizing the legacy method of drawing the shadow is very expensive and slow :|

**Comment by xiphirx** [comment]
Actually, found a workaround! Try out the snapshot and let me know what you think.

**Comment by matecode** [comment]
Perfect that you found a way. I can confirm its working now. Thanks for fixing
