### ISSUE TITLE
Change outer circle alpha

### ISSUE THREAD

**Issue by hpimentel** [KeepSafe/TapTargetView#152]
Is there an easy way to change the outer circle alpha? I wasn't able to find a setter with the given set of APIs.

**Comment by xiphirx** [comment]
Yup, colors passed to a `TapTarget` are in the AARRGGBB format, so if you would like to modify the alpha, just modify the AA portion like so:
```
TapTargetView.showFor(this,
    TapTarget.forView(findViewById(R.id.target), "title", "description")
        .outerCircleColorInt(0x50FF0000), // 31% red
    new TapTargetView.Listener() { ... });
```

**Comment by hpimentel** [comment]
Thanks, I've tried that approach and also through colors.xml but in both cases the transparency looks the same regardless of the AA value I use. If this is supposed to work, I assume there's something wrong elsewhere in my implementation so I'll keep digging.

**Comment by xiphirx** [comment]
The given outer circle color's alpha will end up being multiplied by 96%, that is probably what you're running into. Did you want to use a completely solid color?

**Comment by hpimentel** [comment]
Oh that would explain it. In my implementation I'm trying to get a lighter transparency.

**Comment by xiphirx** [comment]
I see. Yeah that final alpha multiplication is not immediately clear... Perhaps the library should have a baked in default alpha value. I'll look into improving this API.

**Comment by hpimentel** [comment]
That would be a great addition to help personalize the targets more. Thanks!
