### ISSUE TITLE
Resources$NotFoundException crash with 1.9.0

### ISSUE THREAD

**Issue by julioz** [KeepSafe/TapTargetView#156]
- [x] I have verified the issue exists on the latest version
- [x] I am able to reproduce it

Not sure why this is happening, but upgrading from 1.7.0 to 1.9.0 was all I did and everytime a `TapTargetView` should appear, the crash occurs. 
Some people mention [setting a fixed ID for dynamically generated views](http://stackoverflow.com/questions/15262261/android-content-res-resourcesnotfoundexception-unable-to-find-resource-id-0xf) but honestly I don't understand why that could fix this. Unfortunately, I didn't have time to test it myself.

**Version used:**
1.9.0

**Stack trace:**
```
android.content.res.Resources$NotFoundException: Resource ID #0xffffffff
    at android.content.res.Resources.getValue(Resources.java:1351)
    at android.content.res.Resources.getDimension(Resources.java:620)
    at com.getkeepsafe.taptargetview.TapTarget.dimenOrSize(TapTarget.java:472)
    at com.getkeepsafe.taptargetview.TapTarget.titleTextSizePx(TapTarget.java:454)
    at com.getkeepsafe.taptargetview.TapTargetView.<init>(TapTargetView.java:400)
    at com.getkeepsafe.taptargetview.TapTargetView.showFor(TapTargetView.java:165)
```

**Android version:**
Android M

This is the code that I use for `show`ing the `TapTargetView`:
```
TapTarget.forView(targetView, title, description)
    .outerCircleColor(R.color.white)
    .targetCircleColor(R.color.orange)
    .textColor(R.color.black)
    .transparentTarget(false)
    .titleTextDimen(R.dimen.medium_primary_text_size)
    .descriptionTextDimen(R.dimen.medium_secondary_text_size)
    .textTypeface(getFont(context, MY_CUSTOM_FONT_TYPEFACE));
```
but since the only change I did was the dependency version, I believe the issue must be inside the library unfortunately.

**Comment by xiphirx** [comment]
Does `R.dimen.medium_primary_text_size` point to a value or does it point to a reference? If you downgrade to 1.7 or 1.8, does it still occur?

The stack trace you posted does not seem to be a library issue, but rather that a reference you're dereferencing doesn't exist in the theme

**Comment by julioz** [comment]
It doesn't occur with 1.7.0 as that is the version I currently have in production.
The reference is a regular dimens resource, though:
```
<dimen name="medium_primary_text_size">20sp</dimen>
```

Maybe there's something obvious about this that I'm not seeing 🤔

**Comment by xiphirx** [comment]
Can you try running `context.getResources().getDimension(R.dimen.medium_primary_text_size);` and seeing if that throws the same exception?

**Comment by julioz** [comment]
It doesn't crash. I am able to refer to that resource normally. The TapTargetView shows correctly if I remove the two lines that mess with `dimens` resources (`titleTextDimen` and `descriptionTextDimen`).
I believe it might be something related to how `dimenOrSize` works. Is that a new method?

**Comment by xiphirx** [comment]
This was a simple oversight on my part @julioz 1.9.1 has been released to fix this issue.

**Comment by julioz** [comment]
@xiphirx Alright, no problem. Thanks for the quick fix, I'll try it out as soon as the artifact is out and then get back to you to report if it works. 👍

**Comment by julioz** [comment]
@xiphirx Just confirming it actually fixed it. Thanks again!
