### ISSUE TITLE
Views on google maps disappearing

### ISSUE THREAD

**Issue by ga2** [KeepSafe/TapTargetView#159]
- [x] I have verified the issue exists on the latest version
- [x] I am able to reproduce it

Hello I am using this wonderful TapTargetView with google maps
my component tree is

RelativeLayout
-> Fragment(for map)
--> Floating Action Button

the problem is when I use TapTarget with FAB, FAB disappears
I think it is related to maps (or to the fragment) because it works well in the other activities

**Comment by xiphirx** [comment]
I cannot reproduce this. I need your layout xml and relevant styles, if any, in addition to the code youre using to show the `TapTargetView`

I also need to know which version of android this is happening on, and which version of maps youre using

**Comment by ga2** [comment]
I checked better my code and I've found a big mistake made by me; I am so sorry xiphirx

keep up the good work
