### ISSUE TITLE
TapTargetView positioning on (0,0) on some devices

### ISSUE THREAD

**Issue by ANPez** [KeepSafe/TapTargetView#16]
When targetting a view inside a recyclerView, .getLocationInScreen returns always zero on some devices

**Comment by xiphirx** [comment]
Do you have a quick sample of code that would reproduce the problem? Is the view you're targeting visible and present in the layout?

**Comment by ANPez** [comment]
I'm using it like so:
`      tapTargetView = new TapTargetView.Builder(activity)
              .title(title)
              .description(description)
              .outerCircleColor(R.color.colorAccent)
              .targetCircleColor(R.color.tutorialBackground)
              .textColor(R.color.colorPrimary)
              .dimColor(R.color.tutorialBackground)
              .tintTarget(false)
              .drawShadow(true)
              .cancelable(false)
              .showFor(recyclerView.getChildAt(0).findViewById(R.id.target1));
`

I'm sure I'm executing this when the view is loaded. Also, I've tried a .postDelayed({}, 3000) just to make sure the view is on screen. I can see it, but the tap is centering on (0,0)

**Comment by xiphirx** [comment]
Hi, I just tried to replicate the issue, however I was unable to. I tried utilizing your method of doing `recyclerView.getChildAt(0).findViewById` to locate the view, and the tap target appeared and targed the view correctly.

What type of view has the id `target1` in your code?

**Comment by ANPez** [comment]
It is an imageview. It works fine on a Nexus 5 with Android 6.0.1, however it does not work on a Nexus 7 with Android 4.4 and a Nexus 5X running 7.0. I tried . getPositionOnWindow() and also seems to return 0,0.

**Comment by xiphirx** [comment]
That is very odd... I'm testing on a Nexus 6P running 7.0 

What version of the support library are you using? If the view is reporting that it is at (0, 0) then there's not much I can do from my end...

**Comment by ANPez** [comment]
I'm using the latest version. It's very weird. I'll do some more tests and let you know. Thank you for your quick answer, you're the best!

**Comment by xiphirx** [comment]
No problem, please open an issue when you have more information.
