### ISSUE TITLE
Circle shifting

### ISSUE THREAD

**Issue by Everhustle** [KeepSafe/TapTargetView#160]
- [+] I have verified the issue exists on the latest version
- [+] I am able to reproduce it

**Version used:** latest

**Stack trace:** don't know what's this

**Android version:** 6.0.1

Hi. Thank you for such a beatiful lib firstly. I have a "match_parent" edit_text field. When I target it, my circle stands at the middle. I need to shift it to the field start. How can I do this?

**Comment by xiphirx** [comment]
Currently you would have to do this via `TapTarget.forBounds(...)` and using the views' bounds.

**Comment by Everhustle** [comment]
So I will still have a round circle not ellipse?

**Comment by xiphirx** [comment]
It will always be a circle. The circle will be positioned in the center of the given bounds. If you only wish to target the first part of the `EditText` then you should limit the bounds to the area that you care about. You may also just pass in a 1x1 bound rect and that should work as well. The 1x1 will serve as the center point of the `TapTarget` circle.
