### ISSUE TITLE
Stop Sequence  

### ISSUE THREAD

**Issue by clempe** [KeepSafe/TapTargetView#163]
Is there a possibility to stop/abort a Sequence via a method call?

**Comment by xiphirx** [comment]
There isn't currently, but there certainly should. I'll look into adding it soon!

**Comment by xiphirx** [comment]
When you would call `TapTargetSequence.stop()` would you expect your `TapTargetSequence.Listener#onSequenceCanceled(TapTarget)` method to be called?

**Comment by clempe** [comment]
Yes something like that, but without the check if  `TapTargetSequence.continueOnCancel` is true.

I've `TapTargetSequence.continueOnCancel` and `TapTargetSequence.considerOuterCircleCanceled` set to true, so there is no other possibility to cancle the Sequence.

**Comment by nitin070895** [comment]
Hey!

Have you added the TapTargetSequence.stop() method?

I want to continue the sequence on clicking outer circle and on clicking outside the outer circle the sequence should cancel. Is there any way of doing that.
