### ISSUE TITLE
UnsupportedOperationException on API 15

### ISSUE THREAD

**Issue by marbat87** [KeepSafe/TapTargetView#164]
- [X] I have verified the issue exists on the latest version
- [X] I am able to reproduce it

There is an issue with clipPath on API 15 because it is not supported with hardware acceleration enabled.

**Version used:**
1.9.1

**Stack trace:**
`
Exception java.lang.UnsupportedOperationException:
android.view.GLES20Canvas.clipPath (GLES20Canvas.java:412)
com.getkeepsafe.taptargetview.TapTargetView.onDraw ()
android.view.View.draw (View.java:11015)
android.view.View.getHardwareLayer (View.java:10253)
android.view.ViewGroup.drawChild (ViewGroup.java:2947)
android.view.ViewGroup.dispatchDraw (ViewGroup.java:2573)
android.view.View.draw (View.java:11018)
android.widget.FrameLayout.draw (FrameLayout.java:450)
com.android.internal.policy.impl.PhoneWindow$DecorView.draw (PhoneWindow.java:2137)
android.view.View.getDisplayList (View.java:10454)
android.view.HardwareRenderer$GlRenderer.draw (HardwareRenderer.java:851)
android.view.ViewRootImpl.draw (ViewRootImpl.java:2034)
android.view.ViewRootImpl.performTraversals (ViewRootImpl.java:1748)
android.view.ViewRootImpl.handleMessage (ViewRootImpl.java:2583)
android.os.Handler.dispatchMessage (Handler.java:99)
android.os.Looper.loop (Looper.java:137)
android.app.ActivityThread.main (ActivityThread.java:4506)
java.lang.reflect.Method.invokeNative (Method.java)
java.lang.reflect.Method.invoke (Method.java:511)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:809)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:576)
dalvik.system.NativeStart.main (NativeStart.java)
`

**Android version:**
4.0.3

**Comment by seba123neo** [comment]
Same issue here...API 15

**Comment by xiphirx** [comment]
Thanks for the reports, working on a fix.

**Comment by xiphirx** [comment]
@marbat87 please try out the snapshot build and verify that you can no longer reproduce please. Thanks!

**Comment by seba123neo** [comment]
yes, now works, thanks

**Comment by marbat87** [comment]
@xiphirx I confirm that now it works.

Thanks

**Comment by niqueco** [comment]
Hi! Could you please consider releasing a new version? This is crashing my app in production and now I find this have been fixed for months.. Thanks, and thanks for this library!

**Comment by niqueco** [comment]
You should at least consider adding a warning to the README that this library crashes old Android versions, so nobody else gets burned as I did. (It would be simpler to release the fix instead, of course)

**Comment by xiphirx** [comment]
You can use a snapshot (from https://jitpack.io/#KeepSafe/TapTargetView/-SNAPSHOT) if you need a fix immediately. I'm a bit busy right now to go through and ensure the current code is releasable

**Comment by niqueco** [comment]
Thanks for the tip, I'll look into doing that.

**Comment by niqueco** [comment]
This is the snapshot I use in build.gradle:

```
compile 'com.github.KeepSafe:TapTargetView:4d36558'
```

It's very unfortunate we have to do this, though.

**Comment by petrnalevka** [comment]
Many thanks,I will give it a try..I also think reverting to 1.8.0 would also work IMHO..
