### ISSUE TITLE
Makes RecyclerView scroll down on dismiss

### ISSUE THREAD

**Issue by Gericop** [KeepSafe/TapTargetView#170]
- [ ] I have verified the issue exists on the latest version
- [ ] I am able to reproduce it

**Version used:** 1.9.1

**Stack trace:** N/A

**Android version:** 7.0

Found an interesting bug(?): whenever the `TapTargetView` gets dismissed (either the user cancels it or on back pressed), it scrolls my `RecyclerView` to kinda like a certain position. I don't really understand why this is happening, but it's the lib for sure as I tested with another feature discovery lib and it didn't show this behavior. The targeted view is inside a Toolbar. The structure is something like this:
```
CoordinatorLayout
- AppBarLayout
  - Toolbar
    - TextView (this is the target)
- SwipeRefreshLayout
  - RecyclerView
```
This is a fragment's layout and the fragment is added to an Activity, which has a `DrawerLayout` that contains the fragment container `FrameLayout`.

**Comment by xiphirx** [comment]
Are you able to isolate the issue and provide a sample that reproduces the issue?
