### ISSUE TITLE
Ripple effect not working on Kitkat 4.4.4 (API 19)

### ISSUE THREAD

**Issue by chainchelliah** [KeepSafe/TapTargetView#173]
- [ ] I have verified the issue exists on the latest version
- [ ] I am able to reproduce it

While start sequence ripple not working. 
Looking forward to your reply.

**Comment by Zhuinden** [comment]
Is it supposed to? Ripples were added to Android in API 21

**Comment by xiphirx** [comment]
Do you have your animation timing modified? Do you see the expanding animation?
