### ISSUE TITLE
How to make status bar transparent when showing TapTargetView

### ISSUE THREAD

**Issue by samlu** [KeepSafe/TapTargetView#175]
You can see that the system status bar is transparent when showing the NavigationView (Android support design package).

Is there a way to make the status bar transparent when showing TapTargetView?

**Comment by clempe** [comment]
You can use the `TapTargetView.Listener` and override the `onTargetClick(TapTargetView view)` as shown, [here](https://github.com/KeepSafe/TapTargetView#simple-usage).

**Comment by samlu** [comment]
It looks like that you misunderstood my question.

Please check the attached image.
I'd like to show TapTargetView under a semi-transparent status bar, similar to we open the righ navigation view by using the android.support.design.widget.NavigationView

![Uploading TapTargetView.png…]()

**Comment by samlu** [comment]
![taptargetview](https://user-images.githubusercontent.com/1866938/27328518-fd0b5470-55e4-11e7-8ae3-562eea806827.png)

here is the image.

**Comment by clempe** [comment]
The only solution i could suggest, is to disable the StatusBar while using TapTargets.

**Comment by xiphirx** [comment]
Sorry, this is against the material guidelines and so the library does not support it. If I remember correctly, this change https://github.com/KeepSafe/TapTargetView/commit/59c29f46fc9db87165c9a8abc6661dcfc4fb158a is the one that prevented this behavior, so feel free to fork + revert and try it out.

**Comment by ShakilAhmedShaj** [comment]
> It looks like that you misunderstood my question.
> 
> Please check the attached image.
> I'd like to show TapTargetView under a semi-transparent status bar, similar to we open the righ navigation view by using the android.support.design.widget.NavigationView

can anybody tell me how to add target to the navigation drawer burger icon? I cant find this burger icon view, how to implement this like shown in this image?
