### ISSUE TITLE
Xamarin Binding Library

### ISSUE THREAD

**Issue by btripp** [KeepSafe/TapTargetView#176]
Hey,

Just wanted to let you know that I made a Xamarin Binding Library for this. Now users can use your work in a Xamarin Android project. Here is the link if you wanted to put it on your readme.

https://www.nuget.org/packages/Xamarin.TapTargetView

Thanks,
Brandon

**Comment by xiphirx** [comment]
Thank you! Added to the readme in 565cb7cc492fa804d9e5dcd362de3765c6beebb2
