### ISSUE TITLE
How to click outer target and to go next sequence ?

### ISSUE THREAD

**Issue by valterh4ck3r** [KeepSafe/TapTargetView#178]
- [x] I have verified the issue exists on the latest version
- [ ] I am able to reproduce it

How to click outer target and to go next sequence ?

I need that the user click outer target area but not cancel the sequence, only go to next sequence.

**Version used:**

Date : 17/06/2017

**Stack trace:**

No stack trace. This is not a error.

**Android version:**
Any version.

**Comment by clempe** [comment]
If I understand correctly, if the users click on the outer circle, the sequence should show to the next TapTarget in the sequence?
Just do this:
`sequence.continueOnCancel(true);`
`sequence.considerOuterCircleCanceled(true);`

**Comment by valterh4ck3r** [comment]
Exactly , thanks
