### ISSUE TITLE
Cannot use TapTargetSequence with Gradle

### ISSUE THREAD

**Issue by rubin-parakhi** [KeepSafe/TapTargetView#18]
Could not use TapTargetSequence when using with **Gradle**. Also TagTargetView in EditText seems unfit

**Comment by xiphirx** [comment]
TapTargetSequence is not released yet. 

I'm going to need to see a screenshot for the EditText issue

**Comment by rubin-parakhi** [comment]
Thanks for this awesome library. Really liked what is currently offered.
Sending you the snap in case of edit text.

**Comment by xiphirx** [comment]
Ah. The issue is that the library and the guidelines only support icons of maximum size 88dp x 88dp, which is why it doesn't look proper. You're not using it for its intended purpose unfortunately

**Comment by rubin-parakhi** [comment]
So the library is just limited to buttons, fabs and icon buttons or text with small width. Thanks anyway for this awesome lib

**Comment by xiphirx** [comment]
I wouldn't mind supporting more shapes, I just don't know when it will happen. If you would like to try to add the support so you can use it sooner, I'd happy to review a PR

**Comment by surajsingh-itian** [comment]
Hello Hilal,

When TapTargetSequence will be available as part library.

**Comment by xiphirx** [comment]
It's a part of the 1.2.0 milestone, https://github.com/KeepSafe/TapTargetView/milestone/1

Once all issues are fixed, 1.2.0 will be released.

If you do not want to wait, you can use a [snapshot](https://jitpack.io/#KeepSafe/TapTargetView/-SNAPSHOT).

**Comment by surajsingh-itian** [comment]
Thank you Hilal
