### ISSUE TITLE
Target spinner's item

### ISSUE THREAD

**Issue by LloydBlv** [KeepSafe/TapTargetView#182]
Is there anyway to Target an android's spinner items?

**Comment by xiphirx** [comment]
If you're not using your own Adapter, then you might have to resort to Reflection as I did in [ToolbarTapTarget.java](https://github.com/KeepSafe/TapTargetView/blob/master/taptargetview/src/main/java/com/getkeepsafe/taptargetview/ToolbarTapTarget.java)

If you are using your own adapter, then you have control over the views supplied and should be able to target the ones created in your adapter.
