### ISSUE TITLE
Make TapTargetView.Listener an Interface !

### ISSUE THREAD

**Issue by gouy-elliot** [KeepSafe/TapTargetView#188]
Hello there,

Not really a bug : Could you implement the TapTargetView.Listener as an interface instead of a class ?

Thx,
Elliot.

**Comment by xiphirx** [comment]
Sure, why not.

**Comment by xiphirx** [comment]
Actually, this will require breaking changes and a bit of work to make it work properly. Will have to reschedule for v2.

**Comment by xiphirx** [comment]
Tracking in #227
