### ISSUE TITLE
View is null when trying to find menu item in Action mode toolbar

### ISSUE THREAD

**Issue by lamprosgk** [KeepSafe/TapTargetView#189]
Hi, trying to find a view in action mode where the contextual menu is shown, but seems like the view can't be found when using `TapTarget.forToolbarMenuItem()`, I get `java.lang.IllegalArgumentException: Given null view to target`

**Comment by xiphirx** [comment]
You need to ensure your menu is fully inflated before you try to target a menu item.

**Comment by lamprosgk** [comment]
It is inflated, using the `MenuInflater`
