### ISSUE TITLE
Can't set MenuItem as target without inflating menu from XML.

### ISSUE THREAD

**Issue by dexion** [KeepSafe/TapTargetView#190]
- [x] I have verified the issue exists on the latest version
- [x] I am able to reproduce it

**Version used:**
1.9.1

**Stack trace:**
`java.lang.IllegalArgumentException: Given null view to target`
**Android version:**
Any

In my fragment I manually create menu (not use inflater):
```JAVA
static final int MARK_ID = 2;
static final int SHARE_ID = 3;

@Override
public void onCreateOptionsMenu(Menu menu, MenuInflater inflater) {
    MenuItem markItem = menu.add(
            Menu.NONE,
            MARK_ID,
            Menu.FIRST,
            null);
    markItem.setShowAsAction(MenuItem.SHOW_AS_ACTION_ALWAYS);

    MenuItem shareItem = menu.add(
            Menu.NONE,
            SHARE_ID,
            Menu.FIRST,
            null);
    shareItem.setShowAsAction(MenuItem.SHOW_AS_ACTION_ALWAYS);
}
```

After that I try to set TapTarget:
```
TapTarget.forToolbarMenuItem(((MyActivity) getActivity()).getToolbar(), MARK_ID, "title", "description")
                                .outerCircleColor(R.color.colorAccent)
                                .targetCircleColor(R.color.icons)
                                .drawShadow(true)
                                .cancelable(false)
```
And I get error
`java.lang.IllegalArgumentException: Given null view to target`

I don't want inflate menu from XML because so many conditions for create each item. What should I do in this case?

**Comment by xiphirx** [comment]
Since youre using an ActionBar, you need to delay your tap target quite a bit. See #168

**Comment by homeandroid-ir** [comment]
Hi how can i get to me
toolbar menu toogle
Or the icons I put to me.
