### ISSUE TITLE
Dialogs are supported for single Targets, but not for Sequences

### ISSUE THREAD

**Issue by danprado** [KeepSafe/TapTargetView#191]
- [x] I have verified the issue exists on the latest version
- [x] I am able to reproduce it

**Version used:** 1.9.1

When showing a TapTarget for a single target, the lib accepts a `Dialog` as a parameter and it works fine. This is not true for `TapTargetSequence()` though, since it only accepts an `Activity` as a parameter.

**Comment by xiphirx** [comment]
Are you expecting to mix and match between Dialogs and Views in your sequence? If so, support for this would require some pretty major refactoring...

**Comment by danprado** [comment]
Hi @xiphirx! Sorry for the delay! 
I don't want to mix them. I just want to show a sequence inside an active `Dialog`.
If I start a sequence inside an active `Dialog` passing the `Activity` as the parameter for the `TapTargetSequence()` it shows behind the dialog.
I'd like to have something like `TapTargetSequence(Dialog dialog)`.
Does that make sense?
Thanks!
