### ISSUE TITLE
Programmatically cancel

### ISSUE THREAD

**Issue by Melden** [KeepSafe/TapTargetView#197]
- [ +] I have verified the issue exists on the latest version
- [ +] I am able to reproduce it

I need to call TapTargetView.dismiss grammatically but this method is not static as showFor is. I cannot call onTargetCancel in Listener because it is in a different place in the code. 
I need to call TapTargetView.dismiss  in some cases on onDetach() and onDestroy().

**Version used:** 1.9.1

**Stack trace:**

**Android version:** 7.1.2

**Comment by xiphirx** [comment]
You can get an instance of `TapTargetView` as a return value from `showFor`, you can then call `dismiss()` on that instance when needed.
