### ISSUE TITLE
Sequence construction

### ISSUE THREAD

**Issue by gaara87** [KeepSafe/TapTargetView#2]
It would be great if there was a way to construct a sequence of these guides

**Comment by xiphirx** [comment]
Sure thing. Any preferred method of sequence creation?

**Comment by gaara87** [comment]
Use the same Builder pattern.

TapTargetSequence.Builder()
.step(tapTargetView1)
.step(tapTargetView2)...
.skipIfAnyStepIsCanceled()

This is from the top of my mind :)

**Comment by gaara87** [comment]
@xiphirx great job! i'll check it out 👍
