### ISSUE TITLE
java.lang.IllegalArgumentException in Google Play Crash reporting

### ISSUE THREAD

**Issue by Luklek** [KeepSafe/TapTargetView#200]
**Version used:** 1.9.1

java.lang.IllegalArgumentException: 	at com.getkeepsafe.taptargetview.ViewTapTarget.<init>(ViewTapTarget.java)
   at com.getkeepsafe.taptargetview.ToolbarTapTarget.<init> (ToolbarTapTarget.java)
   at <OR> com.getkeepsafe.taptargetview.ToolbarTapTarget.<init> (ToolbarTapTarget.java)
   at com.getkeepsafe.taptargetview.TapTarget.forToolbarNavigationIcon (TapTarget.java)
   at <OR> com.getkeepsafe.taptargetview.TapTarget.forToolbarMenuItem (TapTarget.java)
   at <OR> com.getkeepsafe.taptargetview.TapTarget.forView (TapTarget.java)
   at <OR> com.getkeepsafe.taptargetview.TapTarget.transparentTarget (TapTarget.java)
   at <OR> com.getkeepsafe.taptargetview.TapTarget.outerCircleAlpha (TapTarget.java)
   at <OR> com.getkeepsafe.taptargetview.TapTarget.dimColor (TapTarget.java)
   at <OR> com.getkeepsafe.taptargetview.TapTarget.onReady (TapTarget.java)
   at <OR> com.getkeepsafe.taptargetview.TapTarget.bounds (TapTarget.java)
   at <OR> com.getkeepsafe.taptargetview.TapTarget.outerCircleColorInt (TapTarget.java)
   at <OR> com.getkeepsafe.taptargetview.TapTarget.colorResOrInt (TapTarget.java)
   at <OR> com.getkeepsafe.taptargetview.TapTarget.dimenOrSize (TapTarget.java)
   at theme.utils.TapIntroHelper$1.run (TapIntroHelper.java)
   at android.os.Handler.handleCallback (Handler.java:815)
   at android.os.Handler.dispatchMessage (Handler.java:104)
   at android.os.Looper.loop (Looper.java:194)
   at android.app.ActivityThread.main (ActivityThread.java:5631)
   at java.lang.reflect.Method.invoke (Method.java)
   at java.lang.reflect.Method.invoke (Method.java:372)
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:959)
   at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:754)

I see this error in Google Play dashboard. On average 2 impacted users every 2000 downloads.
I know it's very little % and not so important, but still wanted to report it in case may be useful.
Thanks :)

**Comment by xiphirx** [comment]
That means the the library wasnt able to retrieve the navigation icon view to use, and so it got `null` back. I would make sure that you inflate your toolbar properly. Outside of that, this might be a device specific issue, so I'll need more information.

**Comment by Luklek** [comment]
It seems to happen across many low-end devices (Samsung J serie and similar) and Android OS versions (4.2 to 6). Other than this I have no other info (also it affects just 1 user every 1000... so it isn't really a problem I think)

**Comment by Luklek** [comment]
I tried to check if toolbar is null and in case don't show the intro. But I still get the same error.

public void showTapIntroMain(@NonNull Context context) {

        final Handler handler = new Handler();
        final AppCompatActivity activity = (AppCompatActivity) context;

        handler.postDelayed(new Runnable() {
            @Override
            public void run() {
                final Toolbar toolbar = (Toolbar) activity.findViewById(R.id.toolbar);
                final ImageView scroll = (ImageView) activity.findViewById(R.id.scroll_gallery);
                if (toolbar == null) {
                    mFirebaseAnalytics.logEvent("tapintro_would_crush", null);
                    return;
                }
                final TapTargetSequence sequence = new TapTargetSequence(activity)
                        .targets(
                                TapTarget.forToolbarMenuItem(toolbar, R.id.gift_image, activity.getString(R.string.tap_apply_title), activity.getString(R.string.tap_apply_desc)).cancelable(false).dimColor(android.R.color.black).id(1),
                                TapTarget.forToolbarNavigationIcon(toolbar, activity.getString(R.string.tap_menu_title), activity.getString(R.string.tap_menu_desc)).cancelable(false).id(2),
                                TapTarget.forToolbarMenuItem(toolbar, R.id.action_help, activity.getString(R.string.tap_help_title), activity.getString(R.string.tap_help_desc)).cancelable(false).id(3)
                        )
                        .listener(new TapTargetSequence.Listener() {
                            // This listener will tell us when interesting(tm) events happen in regards
                            // to the sequence
                            @Override
                            public void onSequenceFinish() {
                                scroll.setVisibility(View.VISIBLE);
                                TapTargetView.showFor(activity, TapTarget.forView(scroll, activity.getString(R.string.tap_scroll_title), activity.getString(R.string.tap_scroll_desc))
                                        .dimColor(android.R.color.black)
                                        .transparentTarget(true)
                                        .cancelable(false)
                                        .outerCircleAlpha(1f)
                                        .targetRadius(82), new TapTargetView.Listener() {
                                    @Override
                                    public void onTargetClick(TapTargetView view) {
                                        super.onTargetClick(view);
                                        scroll.setVisibility(View.GONE);
                                        ShowInterstitialIntro();
                                    }
                                    @Override
                                    public void onOuterCircleClick(TapTargetView view) {
                                        super.onOuterCircleClick(view);
                                        //super.onTargetClick(view);
                                    }
                                    @Override
                                    public void onTargetDismissed(TapTargetView view, boolean userInitiated) {
                                        scroll.setVisibility(View.GONE);
                                        ShowInterstitialIntro();
                                    }
                                });
                            }
                            @Override
                            public void onSequenceStep(TapTarget lastTarget, boolean targetClicked) {
                            }
                            @Override
                            public void onSequenceCanceled(TapTarget lastTarget) {
                                scroll.setVisibility(View.VISIBLE);
                                TapTargetView.showFor(activity, TapTarget.forView(scroll, activity.getString(R.string.tap_scroll_title), activity.getString(R.string.tap_scroll_desc))
                                        .dimColor(android.R.color.black)
                                        .transparentTarget(true)
                                        .cancelable(false)
                                        .outerCircleAlpha(1f)
                                        .targetRadius(82), new TapTargetView.Listener() {
                                    @Override
                                    public void onTargetClick(TapTargetView view) {
                                        super.onTargetClick(view);
                                        scroll.setVisibility(View.GONE);
                                        ShowInterstitialIntro();
                                    }
                                    @Override
                                    public void onOuterCircleClick(TapTargetView view) {
                                        super.onOuterCircleClick(view);
                                        //super.onTargetClick(view);
                                    }
                                    @Override
                                    public void onTargetDismissed(TapTargetView view, boolean userInitiated) {
                                        scroll.setVisibility(View.GONE);
                                        ShowInterstitialIntro();
                                    }
                                });
                            }
                        });
                sequence.start();
            }
        }, 100);

    }

**Comment by Luklek** [comment]
It was the same problem as here: https://github.com/KeepSafe/TapTargetView/issues/168
