### ISSUE TITLE
How can we show guide view in TextView which show its Hint text in Guide view.

### ISSUE THREAD

**Issue by AmanChugh** [KeepSafe/TapTargetView#201]
I have an TextView in Toolbar with match_parent width. Guide View how in middle .I want to show it over hint. Please help

**Comment by xiphirx** [comment]
`TapTarget#forBounds(...)` if you want to target a specific area

**Comment by AmanChugh** [comment]
When I am trying with forBounds(..) then It created it on left top corner.

**Comment by xiphirx** [comment]
For the bounds, you will need to calculate exactly where to place the target. For the FAB, don't tint the target.
