### ISSUE TITLE
[bug] Second TapTarget should be present if first was dismissed

### ISSUE THREAD

**Issue by Kolyall** [KeepSafe/TapTargetView#202]
I have verified the issue exists on the latest version
 I am able to reproduce it
```
TapTargetSequence targetSequence = new TapTargetSequence(getActivity())
                .targets(
                       TapTarget.forView(mTextView,"Title","SubTitle").cancelable(true) ,
                       TapTarget.forView(mEditText, "Title", "SubTitle").cancelable(true),
                       TapTarget.forView(mEditText2, "Title", "SubTitle").cancelable(true)
                );
        targetSequence.start();
```
reproduce it:
Run the app
-> First TapTarget is present
Click outside or click ob back button on device to dismiss first TapTarget 
-> First TapTarget is dismissed
[bug]
Second and Third TapTargets are also dismissed
[expected result]
 Second TapTarget should be present

**Version used: 1.9.1**

**Stack trace:**

**Android version 6.0.1:**

**Comment by xiphirx** [comment]
use `TapTargetSequence#continueOnCancel(true)`
