### ISSUE TITLE
Fatal signal 7

### ISSUE THREAD

**Issue by maheshpujala** [KeepSafe/TapTargetView#205]
- [.] I have verified the issue exists on the latest version
- [.] I am able to reproduce it

**Version used:**
1.9.1

**Stack trace:**
google-breakpad: ### ### ### ### ### ### ### ### ### ### ### ### ###
09-06 17:21:18.430 4721-4883/me.maad W/google-breakpad: Chrome build fingerprint:
09-06 17:21:18.430 4721-4883/me.maad W/google-breakpad: 2.0.7
09-06 17:21:18.431 4721-4883/me.maad W/google-breakpad: 1010
09-06 17:21:18.431 4721-4883/me.maad W/google-breakpad: ### ### ### ### ### ### ### ### ### ### ### ### ###
A/libc: Fatal signal 7 (SIGBUS), code 2, fault addr 0x8f095000 in tid 4883 (hwuiTask2)
                                             
                                             [ 09-06 17:21:18.432   191:  191 W/         ]
                                             debuggerd: handling request: pid=4721 uid=10152 gid=10152 tid=4883

**Android version:**
Nougat 7.1

**Comment by xiphirx** [comment]
I dont see how this is related to this library.

**Comment by maheshpujala** [comment]
Thank You for responding .I resolved it.You can close this issue.
