### ISSUE TITLE
Rectangle

### ISSUE THREAD

**Issue by cliffgr** [KeepSafe/TapTargetView#206]
`TapTargetView.showFor(activity, 
                TapTarget.forBounds(new Rect(500,500,800,1300), displayText),
                listener
        );`
Rectangle is not Working as i expected

**Comment by nikulcears** [comment]
> `TapTargetView.showFor(activity, TapTarget.forBounds(new Rect(500,500,800,1300), displayText), listener );`
> Rectangle is not Working as i expected

could you please reply how you have been used this method?
