### ISSUE TITLE
cancelable(true) requires listener to be set, is it intended?

### ISSUE THREAD

**Issue by PrashamTrivedi** [KeepSafe/TapTargetView#21]
In latest lib version `1.0.1`. setting `cancelable(true)` requires listener to be set. It's confirmed by Source where on `setOnClickListener` (and on `setOnLongClickListener`), the method finishes without doing anything if Listener is null. Which IMO contradicts `cancelable(true)` is enough to make this view cancelable. It's not mentioned in doc that `cancelable(true)` alone is good, and we require setListener to work with it. Is this behaviour intended? Or went there accidentally?

In any case I propose any of these three changes.

1. Mention in docs that `cancelable(true)` requires listener to be set.
2. Listener null checks require only when you are dealing with listeners i.e. calling listener method, rest can be fine IMO.
3. Define a default listener, when `cancelable(true)` is called, also set listener be set with that default listener. This will make `cancelable(true)` stand alone without much efforts.

I am giving these suggestions based on what I have seen in the code, I am ok with any of the options taken which can make library more useful. Anyway, thanks a lot for this lib.

**Comment by xiphirx** [comment]
This issue is fixed in the upcoming release of 1.2.0. 1.2.0 will provide a default listener to handle the cancellation if you do not provide one
