### ISSUE TITLE
[Question] How to use TapTargetView for MenuItems and Views inside a drawer?

### ISSUE THREAD

**Issue by Veboy** [KeepSafe/TapTargetView#210]
I tried using `TapTarget.forView` to no avail. Any suggestion would be very welcome.

**Comment by Nevermind-s** [comment]
Same issue here 😞, any solution ?

**Comment by xiphirx** [comment]
I'm assuming you mean MenuItems within a PopupMenu. If thats the case, currently there is no good way to do this. This is the current workaround: #211
