### ISSUE TITLE
TapTargetView is placed behind popup menu

### ISSUE THREAD

**Issue by sowieso2020** [KeepSafe/TapTargetView#211]
I created TapTargetView (or TapTargetSequence) in all of my activities and it displaying well, but for inner views of popup menu, it hides behind my popup menu window! exactly between under activity and popup menu. how can I bring it to top, please? Is parameter of TapTargetSequence ((Activity) context) correct? "context" or "this" occurs error !

**Version used: tapTargetView 4**
**Android version: api25**

    public class Popup_Menu implements OnClickListener {

    PopupWindow popup;      View layout;        Context context;
    WindowManager wm;

    void showPopup(final Activity context) {
        this.context=context;
                        // Inflate the popup_layout.xml
    LinearLayout viewGroup = (LinearLayout) ((Activity) context).findViewById(R.id.popup);
    LayoutInflater layoutInflater = (LayoutInflater) context.getSystemService(Context.LAYOUT_INFLATER_SERVICE);
    layout = layoutInflater.inflate(R.layout.popup_layout_menu, viewGroup);

                        // Creating the PopupWindow
       popup = new PopupWindow(context);
       popup.setContentView(layout);
                        // Clear the default translucent background
       popup.setBackgroundDrawable(new BitmapDrawable());
       popup.showAtLocation(layout, Gravity.BOTTOM, 30 ,0 );

    tapTarget_menu();

    }       /////////////////// close of showPopup() !

     // TapTaget_menu
    public void tapTarget_menu() {
    new TapTargetSequence((Activity) context)
            .targets(
                    TapTarget.forView(layout.findViewById(R.id.chkb_menu_remem), "remember", "last lesson")
                            .targetCircleColor(R.color.sabz_seyedi)
                            .outerCircleColor(R.color.sabzabi_kmrng)
                            .dimColor(R.color.sabz_seyedi)
                            .titleTextSize(22)
                            .descriptionTextSize(16)
                            .textColor(R.color.white)
                            .drawShadow(true)
                            .transparentTarget(true)
                            .cancelable(false)
                            .targetRadius(60),
                    TapTarget.forView(layout.findViewById(R.id.ll_call_menu), "call", "connecting friends!")
                            .targetCircleColor(R.color.sabz_seyedi)
                            .outerCircleColor(R.color.sabzabi_tireh)
                            .dimColor(R.color.sabz_seyedi)
                            .titleTextSize(22)
                            .descriptionTextSize(16)
                            .textColor(R.color.white)
                            .drawShadow(true)
                            .transparentTarget(true)
                            .cancelable(false)
                            .targetRadius(60)
            ).start();
    }

    }

**Comment by PrashantSPol** [comment]
Hello,
This may not be the correct solution, but I can suggest some work-around.

PopupWindow is added to Window whereas TapTargetView is added to decorView, it might be difficult to show it on top of PopupWindow.

you may call following code after popup.showAtLocation(),
```
WindowManager.LayoutParams layoutParams = new WindowManager.LayoutParams(WindowManager.LayoutParams.MATCH_PARENT, WindowManager.LayoutParams.MATCH_PARENT);
        layoutParams.packageName = context.getPackageName();
        layoutParams.format = PixelFormat.TRANSLUCENT;
        layoutParams.flags = WindowManager.LayoutParams.FLAG_ALT_FOCUSABLE_IM;

        TapTarget target = TapTarget.forView(layout.findViewById(R.id.ll_call_menu), "remember", "last lesson");
        target.transparentTarget(true);

        final ViewGroup decor = (ViewGroup) context.getWindow().getDecorView();
        final ViewGroup content = (ViewGroup) decor.findViewById(android.R.id.content);
        final TapTargetView tapTargetView = new TapTargetView(context, decor, content, target, new TapTargetView.Listener(){
            @Override
            public void onTargetClick(TapTargetView view) {
                // open next TargetView
                super.onTargetClick(view);
            }
        });

        ((WindowManager)context.getSystemService(Context.WINDOW_SERVICE)).addView(tapTargetView, layoutParams);
```

**Comment by sowieso2020** [comment]
thank's A lot, this code works like a charm and you save my week.
Good Luck !

۱۳۹۶-۰۷-۱۸ ۱۲:۰۱ +۰۳:۳۰ گرینویچ, Prashant S. Pol <notifications@github.com>:
> Hello,
> This may not be the correct solution, but I can suggest some work-around.
>
> PopupWindow is added to Window whereas TapTargetView is added to decorView,
> it might be difficult to show it on top of PopupWindow.
>
> you may call following code after popup.showAtLocation(),
> ```
> WindowManager.LayoutParams layoutParams = new
> WindowManager.LayoutParams(WindowManager.LayoutParams.MATCH_PARENT,
> WindowManager.LayoutParams.MATCH_PARENT);
>         layoutParams.packageName = context.getPackageName();
>         layoutParams.format = PixelFormat.TRANSLUCENT;
>         layoutParams.flags =
> WindowManager.LayoutParams.FLAG_ALT_FOCUSABLE_IM;
>
>         TapTarget target =
> TapTarget.forView(layout.findViewById(R.id.ll_call_menu), "remember", "last
> lesson");
>         target.transparentTarget(true);
>
>         final ViewGroup decor = (ViewGroup)
> context.getWindow().getDecorView();
>         final ViewGroup content = (ViewGroup)
> decor.findViewById(android.R.id.content);
>         final TapTargetView tapTargetView = new TapTargetView(context,
> decor, content, target, new TapTargetView.Listener(){
>             @Override
>             public void onTargetClick(TapTargetView view) {
>                 // open next TargetView
>                 super.onTargetClick(view);
>             }
>         });
>
>
> ((WindowManager)context.getSystemService(Context.WINDOW_SERVICE)).addView(tapTargetView,
> layoutParams);
> ```
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/KeepSafe/TapTargetView/issues/211#issuecomment-335400547


-- 
تا گردش جهان و دور آسمان بپاست
نور ایزدی همیشه رهنمای ماست

**Comment by xiphirx** [comment]
@PrashantSPol is correct. The workaround is fine for now, but I plan on addressing this in v2 of the library.

**Comment by andy82302** [comment]
android.view.WindowManager$InvalidDisplayException: Unable to add window android.view.ViewRootImpl$W@5e5d48c -- the specified window type -1 is not valid

**Comment by MoustafaElsaghier** [comment]
@xiphirx is it fixed or still not?

**Comment by sowieso2020** [comment]
Yes, answer of PrashantSPol on above is correct.

در تاریخ سه‌شنبه ۹ نوامبر ۲۰۲۱،‏ ۱۵:۳۶ Moustafa ELsaghier <
***@***.***> نوشت:

**Comment by hassanrana** [comment]
> use PrashantSPol's function
> 
> android.view.WindowManager$InvalidDisplayException: Unable to add window android.view.ViewRootImpl$W@5e5d48c -- the specified window type -1 is not valid

getting same error
