### ISSUE TITLE
[Question] Outer circle size/scale

### ISSUE THREAD

**Issue by originx** [KeepSafe/TapTargetView#214]
- [x ] I have verified the issue exists on the latest version
- [x] I am able to reproduce it

**Version used:**
1.9.1
**Stack trace:**
no
**Android version:**
8.0.0

On Google Pixel phone the outer circle radius is not covering the whole screen width. Is this a scaling issue, I do not see any way to set this manually, is there a way to do it?

Thanks

**Comment by xiphirx** [comment]
Where is your target located? The full width outer circle only applies to targets that are within a certain distance to the edge of your App's window.

**Comment by originx** [comment]
![image](https://user-images.githubusercontent.com/452010/31481763-5d22e4a6-af25-11e7-9b80-646a6f1d866d.png)

so I am targeting this magnifier as you can see on the photo in the toolbar.

within a certain distance <-- how is this distance defined

I was comparing it to this
https://material.io/guidelines/growth-communications/feature-discovery.html#feature-discovery-design
https://storage.googleapis.com/material-design/publish/material_v_12/assets/0B4kv-3uZbS1qeGJFTWZ0M2R6ZEE/useredu-er-featuredisc-design-01.png

I presumed it should be overarching the screen borders, but maybe the design guidelines for offsets did not sit well with me yet?

**Comment by xiphirx** [comment]
From that page, "When the prompted action’s tap target is located within 88dp of the screen top or bottom (not including the status and nav bars), place the tap target directly on top of the promoted action." So having it with 88dp of the top is what centers the tap target on the icon. As for extending to the full width, the Pixel has a high enough resolution where its considered "large" (>360dp), and so it doesn't extend all the way.

**Comment by originx** [comment]
makes sense, thanks for the explanation
