### ISSUE TITLE
Rickrolling :D

### ISSUE THREAD

**Issue by heinrichreimer** [KeepSafe/TapTargetView#215]
👍 for [**rickrolling**](https://en.wikipedia.org/wiki/Rickrolling) me while reading an API sample of your library 😄😄😄😄😄😄

A copy of [the related code snippet](https://github.com/KeepSafe/TapTargetView#sequences):
```java
new TapTargetSequence(this)
    .targets(
        TapTarget.forView(findViewById(R.id.never), "Gonna"),
        TapTarget.forView(findViewById(R.id.give), "You", "Up")
                .dimColor(android.R.color.never)
                .outerCircleColor(R.color.gonna)
                .targetCircleColor(R.color.let)
                .textColor(android.R.color.you),
        TapTarget.forBounds(rickTarget, "Down", ":^)")
                .cancelable(false)
                .icon(rick))
```

To honor this, here are the full lyrics from [Musixmatch](https://www.musixmatch.com/lyrics/Rick-Astley/Never-Gonna-Give-You-Up)
> We're no strangers to love
> 
> You know the rules and so do I
> A full commitment's what I'm thinking of
> You wouldn't get this from any other guy
> I just wanna tell you how I'm feeling
> 
> Gotta make you understand
> 
> Never gonna give you up
> Never gonna let you down
> Never gonna run around and desert you
> Never gonna make you cry
> Never gonna say goodbye
> 
> Never gonna tell a lie and hurt you
> We've known each other for so long
> Your heart's been aching but
> You're too shy to say it
> 
> Inside we both know what's been going on
> 
> We know the game and we're gonna play it
> And if you ask me how I'm feeling
> Don't tell me you're too blind to see
> Never gonna give you up
> Never gonna let you down
> Never gonna run around and desert you
> 
> Never gonna make you cry
> Never gonna say goodbye
> Never gonna tell a lie and hurt you
> Never gonna give you up
> Never gonna let you down
> Never gonna run around and desert you
> 
> Never gonna make you cry
> Never gonna say goodbye
> Never gonna tell a lie and hurt you
> (Ooh, give you up)
> 
> (Ooh, give you up)
> (Ooh)
> Never gonna give, never gonna give
> (Give you up)
> 
> (Ooh)
> Never gonna give, never gonna give
> 
> (Give you up)
> We've know each other for so long
> Your heart's been aching but
> You're too shy to say it
> Inside we both know what's been going on
> 
> We know the game and we're gonna play it
> I just wanna tell you how I'm feeling
> Gotta make you understand
> Never gonna give you up
> 
> Never gonna let you down
> Never gonna run around and desert you
> Never gonna make you cry
> Never gonna say goodbye
> Never gonna tell a lie and hurt you
> Never gonna give you up
> Never gonna let you down
> Never gonna run around and desert you
> Never gonna make you cry
> Never gonna say goodbye
> Never gonna tell a lie and hurt you
> Never gonna give you up
> Never gonna let you down
> Never gonna run around and desert you
> Never gonna make you cry
> Never gonna say goodbye
> Never gonna tell a lie and hurt you

**Comment by xiphirx** [comment]
:)
