### ISSUE TITLE
Action bar menu items

### ISSUE THREAD

**Issue by HeinrichReimer** [KeepSafe/TapTargetView#22]
Would be great if we could use menu items as taptarget too.
Maybe take a look at how it's implemented here: https://github.com/amlcurran/ShowcaseView

**Comment by xiphirx** [comment]
What specifically are you looking to qualify when you call into this library to target menu items? The item id? The `MenuItem` instance?

**Comment by HeinrichReimer** [comment]
Excatly

**Comment by xiphirx** [comment]
@HeinrichReimer I've added initial support for Toolbars in #34 . Is this sufficient for you or are you still using an old `ActionBar`?

Please take a look over the PR and let me know if the API is what you were looking for. Example usage can be found in the sample app

**Comment by HeinrichReimer** [comment]
For me that's just enough but I can imagine someone could also want to target action bar views.
And I think that using reflection here can cause issues when Google decides to rename their internal field which can happen at any time without warning.
At least for the navigation item maybe `android.R.id.home` would be an option...
In general I think using reflection in library code is the last option and it's usage should have a big warning in the javadoc.

**Comment by xiphirx** [comment]
Unfortunately it seems like reflection is the only way to do it. The library you mentioned also uses reflection.

**Comment by xiphirx** [comment]
Alright, I have improved `Toolbar` support pretty significantly. I'm going to land the PR for now and think about `ActionBar` support a bit later (probably a few days). If you need this functionality immediately, please consider using a snapshot.
