### ISSUE TITLE
TapTargetView shows under DialogFragment

### ISSUE THREAD

**Issue by barakhadar** [KeepSafe/TapTargetView#221]
- [v] I have verified the issue exists on the latest version
- [v] I am able to reproduce it

**Version used:** 1.10.0

**Stack trace:** None

**Android version:** 6.0.1

I have a DialogFragment that i'm trying to use TapTargetView on it, but it always shows under it, like so:
------ DialogFragment ------
------ TapTargetView -------
------ SomeFragment ------
---------- Activity ----------

Here is my code:

```
TapTargetView.showFor( mDialogFragment.getDialog(),               
                    TapTarget.forView( focusView , "This is a target", "We have the best targets, believe me")
                            .outerCircleColor(R.color.red)      
                            .outerCircleAlpha(0.96f)            
                            .targetCircleColor(R.color.white)   
                            .titleTextSize(20)                  
                            .titleTextColor(R.color.white)      
                            .descriptionTextSize(10)            
                            .descriptionTextColor(R.color.red)  
                            .textColor(R.color.blue)            
                            .textTypeface( Typeface.SANS_SERIF) 
                            .dimColor(R.color.black)            
                            .drawShadow(true)                   
                            .cancelable(false)                  
                            .tintTarget(true)                   
                            .transparentTarget(false)           
                            .targetRadius(60),                  
                    new TapTargetView.Listener() {          
                        @Override
                        public void onTargetClick(TapTargetView view) {
                            super.onTargetClick(view);     
                            clickView.performClick();
                        }
                    });
```

Is there any way to solve this?

**Comment by xiphirx** [comment]
I have replicated your code locally and it is working fine for me. Can you ensure that you're attempting to target a view in the dialog fragment and that you're showing your tap target after the dialog is shown?

**Comment by barakhadar** [comment]
I was initializing TapTargetView right after the DialogFragment onCreateView's. Following your answer, I added a postDelayed with 1000mls, and now it works fine.
Thanks a lot @xiphirx

**Comment by sampalmer** [comment]
I just ran into the same problem, but in my case it was because I passed the activity into `showFor` instead of passing in the dialog.
