### ISSUE TITLE
Status bar shows up

### ISSUE THREAD

**Issue by barakhadar** [KeepSafe/TapTargetView#222]
- [v] I have verified the issue exists on the latest version
- [v] I am able to reproduce it

**Version used:** 1.10.0

**Stack trace:** None

**Android version:** 6.0.1

I have a DialogFragment that i'm trying to use TapTargetView on it, but as the TapTargetView shows up, so is the phone's status bar, even though my app has no status bar... 
Can the status bar be removed somehow? 

P.S. Crazy awesome library!!!

**Comment by xiphirx** [comment]
This is because displaying a TapTargetView on a dialog will utilize its own window. You can giving a themed context that disables the status bar to the targeted dialog, but I'm unsure if it would work. 

Unfortunately this isnt something that is easily fixable with the current API

**Comment by xiphirx** [comment]
Tracking in #227
