### ISSUE TITLE
Feature request: Use TapTarget.id() to only show tap targets once

### ISSUE THREAD

**Issue by heinrichreimer** [KeepSafe/TapTargetView#223]
- [x] I have verified the issue exists on the latest version
- [x] I am able to reproduce it

**Version used:** 1.9.1

**Stack trace:** none

**Android version:** any

What's the purpose of the `id` field and getter/setter in `TapTarget`?`
Or put in another way: Could `TapTargetView` be configured so that it shows each target with a unique ID only once?
I haven't found any code in the sources that makes use of the id property.

**Comment by xiphirx** [comment]
The id is used to identify what target was last seen in a sequence. Having a target shown only once is outside of the scope of this library and should be implemented around the usage.
