### ISSUE TITLE
Text sometimes gets overlapped by navigation bar (in landscape orientation)

### ISSUE THREAD

**Issue by ntoskrnl** [KeepSafe/TapTargetView#224]
- [x] I am able to reproduce it
- [x] I have verified the issue exists on the latest version

**Version used:**
Latest version at the moment,  1.10.0

**Android version:**
Android 8.0, Nexus 6P

When rotating the screen, navigation buttons can overlap the text (as if the navigation bar is not accounted for in some cases). See attached image.

![screenshot_20171113-112857](https://user-images.githubusercontent.com/1446492/32717760-e8e911ae-c86b-11e7-83b6-608d4b96b95b.png)

**Comment by xiphirx** [comment]
Tracking in #227
