### ISSUE TITLE
Add ability to customize paddings of title and description

### ISSUE THREAD

**Issue by ntoskrnl** [KeepSafe/TapTargetView#226]
You can change text color, font size and type face for both the title and the description. However, there is no way to change the gap between them.

I think it would be nice to be able to set custom margins/paddings for title and description or at least control the gap between them.

**Comment by xiphirx** [comment]
I feel like this is starting to defeat the purpose of the library. The guidelines are pretty clear on the spacing, so I don't think I'll plan on adding this.
