### ISSUE TITLE
can't use it in fragment !! 

### ISSUE THREAD

**Issue by Abdelsattar** [KeepSafe/TapTargetView#229]
i used 
`    compile 'com.getkeepsafe.taptargetview:taptargetview:1.10.0'
`

how can i use it for inside fragment TapTargetView.showFor(fragment)

or it's not supported yet  ?

**Comment by xiphirx** [comment]
You need to target a view inside of your fragment.

**Comment by Hararot** [comment]
I'm using Tabfragments with navigation drawer 

I tried to target a view but it dos not work

 `TapTargetView.showFor(mView,                
                TapTarget.forView(mView.findViewById(R.id.checkHomeBroadband), "This is a target", "We have the best targets, believe me")`

when I tried to use `getActivity()`  the target dos not go where the button that I want it to go to,It gos to the main activity view in this case it is the navigation drawer I think
here is a Screenshot:
[https://ibb.co/kMQAAf](url)

I want it to target my button how to do that ?
please help
BTW thank you for this great library
