### ISSUE TITLE
Add ability to select target shape

### ISSUE THREAD

**Issue by Ekalips** [KeepSafe/TapTargetView#231]
Would be nice if there will be an ability to select target shape (eg. rectangle, circle).

**Comment by xiphirx** [comment]
This doesn't conform with the material design guidelines, I dont think I'll be adding in support. Sorry.

**Comment by aMarCruz** [comment]
@xiphirx , please reconsider. Anyway it seems that Google has removed the "on feature discovery" guidelines.
