### ISSUE TITLE
Not working on a fragment

### ISSUE THREAD

**Issue by jianastrero** [KeepSafe/TapTargetView#232]
I have a viewpager which takes fragments as its children, on one fragment i want to show a TapTargetView but it wasn't working

**Version used: 1.10.0**
**Android version: Nougat**

**Comment by xiphirx** [comment]
I'm going to need more information to help you out.

**Comment by joshuagannaban** [comment]
Jian what about our system? Please respond to our msgs please!

**Comment by pnpitms** [comment]
how can you implement TapTarget to be used in a fragment apart from being in Main Activity.  Because some new features are hidden away inside a fragment which will display only if you swipe it like in a viewpager and then some in Main Activity.

**Comment by xiphirx** [comment]
Closing due to lack of detail. Showing a TapTargetView at a certain time it outside of the scope of  this library.
