### ISSUE TITLE
How to change radius of background

### ISSUE THREAD

**Issue by wysgh** [KeepSafe/TapTargetView#234]
https://static.dingtalk.com/media/lALPBbCc1TI_gAzMzc0BaQ_361_205.png_620x10000q90g.jpg?auth_bizType=IM&auth_bizEntity=%7B%22cid%22%3A%22257725717%3A257738343%22%2C%22msgId%22%3A%2244173583941%22%7D&open_id=257738343

**Comment by xiphirx** [comment]
This is not supported and wont be because it goes against the guidelines.
