### ISSUE TITLE
Will the animation durations/delays etc be configurable in the future?

### ISSUE THREAD

**Issue by the-adorno** [KeepSafe/TapTargetView#236]
Hello,

I really like your library, but there is one suggestion for a future release: being able to configure the different animations. Like animation delays and durations. I was able to implement this locally when checking out the sources but wanted to ask if this is planned for a future release as we would rather like to use an offical release of the library.

Thanks in advance!

**Comment by xiphirx** [comment]
Specifically what animation duration are you trying to control? I wasn't planning on supporting this, and I'm not sure it fits very well within the scope of customization options.
