### ISSUE TITLE
Close Feature View On Slide

### ISSUE THREAD

**Issue by emitchel** [KeepSafe/TapTargetView#238]
I use this library for affordances other than buttons, e.g. sliders, etc. Its sometimes confusing for the user to need to tap on a slidable affordance in order to hide the feature view. And believe it or not, they get stuck on it. So maybe allowing the view to dismiss on touch or slide rather a "click"  would be helpful

**Comment by xiphirx** [comment]
Since a `TapTargetView` is just a regular Android `View`, you can implement your own `OnTouchListener` to handle your use-case.
