### ISSUE TITLE
somtimes java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by hannesa2** [KeepSafe/TapTargetView#239]
https://github.com/KeepSafe/TapTargetView/blob/58cf0c642bc701c77d64586719ccfdda067910b3/taptargetview/src/main/java/com/getkeepsafe/taptargetview/ViewUtil.java#L75

He we get sometimes a 

> Fatal Exception: java.lang.IndexOutOfBoundsException Raw Text
> --
>   | android.view.ViewGroup.removeFromArray (ViewGroup.java:4780)
>   | android.view.ViewGroup.removeViewInternal (ViewGroup.java:4965)
>   | android.view.ViewGroup.removeViewInternal (ViewGroup.java:4930)
>   | android.view.ViewGroup.removeView (ViewGroup.java:4861)
>   | com.getkeepsafe.taptargetview.ViewUtil.removeView (ViewUtil.java:75)
>   | com.getkeepsafe.taptargetview.TapTargetView$7.onEnd (TapTargetView.java:342)
>   | com.getkeepsafe.taptargetview.FloatValueAnimatorBuilder$2.onAnimationEnd (FloatValueAnimatorBuilder.java:91)
>

**Comment by xiphirx** [comment]
Please update your version of the library, this has been fixed.
