### ISSUE TITLE
After I used tap tarjet view on fragment, i can't touch buttons, how can I fix it?

### ISSUE THREAD

**Issue by bootavo** [KeepSafe/TapTargetView#242]
In my case I'm using ButtomNavigationBar on MainActivity.class and show inside "HomeFragment",
then "HomeFragment" contain TapTargetVIew

After I used tap tarjet view on fragment, I can't touch buttons, how can I fix it?

**Comment by xiphirx** [comment]
I'm going to need more information to help you out, but my immediate guess is that youre trying to show a TapTargetView on a TapTarget that isn't calling its `onReady` callback.
