### ISSUE TITLE
Static String Variable Returning Null Value

### ISSUE THREAD

**Issue by Diliprocks1986** [KeepSafe/TapTargetView#245]
TapTargetView.showFor(this,// `this` is an Activity
                    TapTarget.forView(findViewById(R.id.fab), "Hi " + fName, "To Add a Travel Click on + Button")
                            .outerCircleColor(R.color.green)      // Specify a color for the outer circle
                            .outerCircleAlpha(0.96f)            // Specify the alpha amount for the outer circle
                            .targetCircleColor(R.color.fuchsia)   // Specify a color for the target circle
                            .titleTextSize(30)                  // Specify the size (in sp) of the title text
                            .titleTextColor(R.color.Darkestpurple)      // Specify the color of the title text
                            .descriptionTextSize(15)            // Specify the size (in sp) of the description text
                            .descriptionTextColor(R.color.maroon)  // Specify the color of the description text
                            .textTypeface(Typeface.SANS_SERIF)  // Specify a typeface for the text
                            .dimColor(R.color.black)            // If set, will dim behind the view with 30% opacity of the given color
                            .drawShadow(true)                   // Whether to draw a drop shadow or not
                            .cancelable(false)                  // Whether tapping outside the outer circle dismisses the view
                            .tintTarget(true)                   // Whether to tint the target view's color
                            .transparentTarget(true)           // Specify whether the target is transparent (displays the content underneath)
                            .targetRadius(60));
        }

**Comment by xiphirx** [comment]
I'm going to need a lot more information to help.
