### ISSUE TITLE
Can't dismiss target when use lib for Dialog

### ISSUE THREAD

**Issue by SyPhamWSC** [KeepSafe/TapTargetView#249]
- [x] I have verified the issue exists on the latest version
- [x] I am able to reproduce it

Hi! Thanks for library!
When I used this with dialog, I can't dismiss target although I used func cancelable(false). I think dialog on top of screen so when I touch on target equivalent to touch dialog.

My English isn't clear, so sorry!

**Comment by xiphirx** [comment]
I'm not sure what you mean. I'm going to need more information. `cancelable(false)` makes it such that you can't cancel the target and need to tap the target to dismiss it.

**Comment by SyPhamWSC** [comment]
I've resolved it. My fault, bro! Thank you!
