### ISSUE TITLE
BottomNavigationView item overrides the tooltip

### ISSUE THREAD

**Issue by dev-android-mobile** [KeepSafe/TapTargetView#250]
- [x] I have verified the issue exists on the latest version
- [x] I am able to reproduce it

When I setting tooltip for BottomNavigationView item its overrides the tooltip. 

```
TapTargetView.showFor(this,
                TapTarget.forView(bottomNavigationView.findViewById(R.id.action_menu), "This is a target", "We have the best targets, believe me"),   
                new TapTargetView.Listener() {
                    @Override
                    public void onTargetClick(TapTargetView view) {
                        super.onTargetClick(view);
                        Toast.makeText(ExampleActivity.this, "Test", Toast.LENGTH_SHORT).show();
                    }
                });
```

**Comment by xiphirx** [comment]
I'm not sure I know what you mean by "its overrides the tooltip", can you explain more?

**Comment by dev-android-mobile** [comment]
Yes, on my screen you can see it
![2](https://user-images.githubusercontent.com/22756710/35183556-d87d7fb6-fdf0-11e7-8be5-53c5005dbf62.png)

**Comment by xiphirx** [comment]
Hmm not sure why the target circle is being clipped... does this happen for any other view?

**Comment by dev-android-mobile** [comment]
I have verified it on others view on this screen and there are also bugs. But in other activity all good. What can be wrong?

**Comment by xiphirx** [comment]
Can you enable debug drawing and take a screenshot with it on? (`TapTargetView.setDrawDebug(true)`)

**Comment by dev-android-mobile** [comment]
![photo_2018-01-24_09-15-58](https://user-images.githubusercontent.com/22756710/35319200-7580879c-00e7-11e8-971a-acef92f5fb8a.jpg)

**Comment by xiphirx** [comment]
Ah, you're tinting your target. Try `.transparentTarget(true)`

**Comment by dev-android-mobile** [comment]
Thank you. It's working good.

**Comment by soheilazimi2018** [comment]
Thank you. It's working good. @xiphirx
