### ISSUE TITLE
RecyclerView Item getting hidden with outer circle color

### ISSUE THREAD

**Issue by MohanRaj22** [KeepSafe/TapTargetView#251]
- [Yes ] I have verified the issue exists on the latest version
- [Yes ] I am able to reproduce it

**Version used:**1.11.0

**Stack trace:**

**Android version:**-7.1.1

When I try to target a RecyclerView's item, The item getting highlighted but actual content hidden with the outer color user.

**Comment by xiphirx** [comment]
I'm not sure what you mean. If you mean that the target circle isnt large enough to cover the whole row, that is intended.

**Comment by MohanRaj22** [comment]
No, I'm using horizontal recycler view. Each item is close to one-fourth of the width and square in shape.
My concern is the item view getting covered up by the outer circle color. With other toolbar menus and TextView, it's working perfectly.

**Comment by MohanRaj22** [comment]
This issue is solved by getting the answer in StackOverflow

I didn't add 

> transparentTarget(true)

Without this, it's working fine with toolbar and another TextView.

Somehow this is mandatory for Recycler but not for other views.
