### ISSUE TITLE
[Question] How to use TapTarget in Navigation Drawer ?

### ISSUE THREAD

**Issue by baudev** [KeepSafe/TapTargetView#252]
I tried many hours for making it work with `TapTarget.forView` but without success... 
I can't succeed in getting the view of an item in the drawer. I thank the solution was there https://github.com/KeepSafe/TapTargetView/issues/210 but it doesn't seem to be the adapted for.

If somebody could give me some suggestions, it would be nice. Thanks in advance.

I tried different things as the following way : 
```
private void setupDrawerContent(NavigationView navigationView) {
        NavigationMenuView  test = ( NavigationMenuView ) navigationView.getChildAt(0);
        Log.e("count", "parent "+ navigationView.getChildCount() + " child" + test.getChildCount());
    }
```
The result was 1 et 0. However, I don't know to what correspond `navigationView.getChildAt(0)`. And still without knowing how to get a menu item view.

**Comment by xiphirx** [comment]
You're going to have to get a reference to the target view somehow. Unfortunately, it seems like this class doesnt expose a public API for doing that. Your next best option is reflection, similar to what I do for the Toolbar here: https://github.com/KeepSafe/TapTargetView/blob/master/taptargetview/src/main/java/com/getkeepsafe/taptargetview/ToolbarTapTarget.java

**Comment by priyakar** [comment]
@baudev I was wondering if you were able to get this working? I dont have much reflection experience so would really appreciate it if you could walk me through it

**Comment by baudev** [comment]
I'm sorry I didn't managed to find a quick solution. And not really needing this feature, I gave up.

**Comment by priyakar** [comment]
Ahh.. No worries. Thank you for your reply. Ill keep trying!!

**Comment by gcantoni** [comment]
`View drawerIcon = toolbar.getChildAt(1);` child depends on how your layout has been created.

`TapTargetView.showFor(this,                 // `this` is an Activity
                TapTarget.forView(drawerIcon, "This is a target", "We have the best targets, believe me")

 );
    }`

Done 💃

**Comment by gcantoni** [comment]
`View drawerIcon = toolbar.getChildAt(1);` child depends on how your layout has been created

Then following simply the README you can pass it in forView method

`TapTarget.forView(drawerIcon, "bla", "blabla")`

Done 👯‍♂️
