### ISSUE TITLE
Text cut off when screen size changes.

### ISSUE THREAD

**Issue by sujan219** [KeepSafe/TapTargetView#259]
After Taptargetview is visible on screen, and the screen size is changed (e.g. if keyboard opens up or collapses), then the whole taptargetview will shift but the text is cut off. Is there anyway I can take care of this case?

**Comment by xiphirx** [comment]
You should prevent the keyboard from appearing when you have a tap target showing. In the case of multi-window its a known issue and something I plan on fixing for v2, see #227
