### ISSUE TITLE
How to use tap target view with titles of tab 

### ISSUE THREAD

**Issue by rohit85111** [KeepSafe/TapTargetView#268]
- [ ] I have verified the issue exists on the latest version
- [ ] I am able to reproduce it

**Version used:**

**Stack trace:**

**Android version:**

**Comment by xiphirx** [comment]
I'm going to need more information if you want help.

**Comment by elizacamber** [comment]
In case someone else has the same question: 
`TapTarget.forView((tabs.getChildAt(0) as ViewGroup).getChildAt(desiredPosition), "Your text here" )`
