### ISSUE TITLE
is it possible to use TapTargetSequence for alert dialog too?

### ISSUE THREAD

**Issue by hargoyal** [KeepSafe/TapTargetView#269]
- [ ] I have verified the issue exists on the latest version
- [ ] I am able to reproduce it

**Version used:1.11.0**

**Stack trace:N/a**

**Android version:8.1.0**

This library works perfect in latest version of android.
I would like to know weather we can use TapTargetSequence for alertDialog buttons?

i tried but fail to do so, do let me know how is it possible?

**Comment by xiphirx** [comment]
Yes a `TapTargetSequence` works for `AlertDialog` Buttons. You should be able to use `AlertDialog.getButton(int)` as the target.

**Comment by hargoyal** [comment]
I tried but circle elevation going down to Alertdialog, PFA
![screenshot_2018-02-22-13-03-24-595_com harshitgoyal saltbuddyintrod](https://user-images.githubusercontent.com/16696932/36525750-4c25cc1c-17d1-11e8-97f4-9df4ca1665fa.png)

My code:

`	TapTargetSequence sequence = new TapTargetSequence(this).targets(
                TapTarget.forView(txt_manage,"Manage","You can manage your trips from here")
						.cancelable(false)
                        .tintTarget(false),
                TapTarget.forView(txt_cancel_trip,"Cancel","You can cancel your trips from here")           
        ).listener(new TapTargetSequence.Listener() {
            @Override
            public void onSequenceFinish() {
				Toast.makeText(IntroDialog.this, "Completed", Toast.LENGTH_SHORT).show();
            }

            @Override
            public void onSequenceStep(TapTarget lastTarget, boolean targetClicked) {
                Toast.makeText(IntroDialog.this, "Clicked on " + lastTarget.id(), Toast.LENGTH_SHORT).show();
            }

            @Override
            public void onSequenceCanceled(TapTarget lastTarget) {

            }
        });

        sequence.start();
    }
`

**Comment by hargoyal** [comment]
I created a custom dialog, It can possible if we provide 
TapTargetView.showFor(dialog,TapTarget.forView(txt_manage,"Manage","You can manage your trips from here")
.cancelable(false)
.tintTarget(false),  new TapTargetView.Listener()......

But when I tried it in TapTargetSequence but it looks like above screenshot.

**Comment by xiphirx** [comment]
`new TapTargetSequence(this)` what is "this" here? It needs to be your dialog.
