### ISSUE TITLE
Option to set the desired color for description text

### ISSUE THREAD

**Issue by lpellegr** [KeepSafe/TapTargetView#27]
It seems there is no option to select the desired color for the text description. It could be something like `descriptionColor`. In that case, renaming `textColor` to `titleColor` would improve understanding.

**Comment by xiphirx** [comment]
That doesn't seem to align well with the guidelines: https://material.google.com/growth-communications/feature-discovery.html

Can you provide a sample where this is done in the guidelines? This library is trying to conform to the standards put into place by Google.

**Comment by lpellegr** [comment]
> That doesn't seem to align well with the guidelines: https://material.google.com/growth-communications/feature-discovery.html

Indeed, there is nothing about text color and opacity in the guidelines for Tap targets. My suggestion is based on a few experiments I made. Depending of the background color and text color used, the alpha value that is automatically applied to the text color is too high and the description is hard to read.

> Can you provide a sample where this is done in the guidelines? This library is trying to conform to the standards put into place by Google.

I understand that you want to conform to Google guidelines but in that case why is elevation (shadow) possible with your TapTargetView implementation? I don't see any Tap targets in Google guidelines that make use of elevation...

**Comment by xiphirx** [comment]
This video from the guidelines shows the tap target with a drop shadow: https://material-design.storage.googleapis.com/publish/material_v_9/0B4kv-3uZbS1qTUxubUFJUXplM1E/engagement-featurediscovery-single-flow.webm

If you want to change the color of the description text, then you can apply a `ForegroundColor` span to your string. If you want to modify the opacity of the description, that is a separate question.

What sample color combos are you having trouble with?

**Comment by xiphirx** [comment]
Changed my mind on this. Since its not explicitly defined it should be allowed. If you need this feature immediately, please use a snapshot.
