### ISSUE TITLE
Guided flow UX?

### ISSUE THREAD

**Issue by i-schuetz** [KeepSafe/TapTargetView#270]
Thanks for making this library!

In the demo I'm seeing that to go to the next step you tap on the currently highlighted button.

Is this good UX / intuitive?

In the material design guideline this doesn't seem to be mentioned. There's only where you tap on the target circle to actually go inside the feature - so the guided flow continues, but nested.

And this is also what I'd probably expect. Tapping on the target circle to go a different place / the next step feels weird.

Did you get this pattern from somewhere or made it up?

An alternative could be to show a "next" button or similar somewhere in the outer circle... or allowing the user to go to the next step by tapping the inner _or_ outer circle. But I see this library is opinionated about this as `showNext()` is not public.

Thoughts?

**Comment by xiphirx** [comment]
There is no language prohibiting the style of guided flow the sample has. It was made up purely for demonstration purposes.

>An alternative could be to show a "next" button or similar somewhere in the outer circle...

This is definitely not part of the guidelines

>or allowing the user to go to the next step by tapping the inner or outer circle

You can control this yourself by `continueOnCancel` and `considerOuterCircleCanceled` or by implementing a custom `TapTargetSequence.Listener`

**Comment by i-schuetz** [comment]
Thanks for the feedback, @xiphirx 

Concerning the tap on the outer circle, the behavior I'm looking for doesn't seem to be solved by what you describe - I want to continue only when tapping on the outer or inner circle, but cancel when tapping outside of the outer circle. Maybe if it was possible to detect the tapped element in `TapTargetSequence.Listener` - I could set the outer circle to cancelling and in the listener step to the next event if it's cancel via tap on outer circle or something like that?
