### ISSUE TITLE
Two taptarget view at once

### ISSUE THREAD

**Issue by burhankhanzada199888** [KeepSafe/TapTargetView#274]
I have two menu items in my toolbar first one is update app and second one is sort items in recyclerview and they are hide by default them when my activity runs i have checked if any new version is available if there is new version is available ti show taptarget view an after that i show sort feature taptarget so this come upn it so there is any way to to make tapraget sequence dynamic not just put targetView in constaratur

**Comment by xiphirx** [comment]
No. Create your sequence after you determine whether or not you have an update tap target to show.
