### ISSUE TITLE
Unable to create fullscreen offset

### ISSUE THREAD

**Issue by Mritunjay10** [KeepSafe/TapTargetView#275]
I am unable to create a fullscreen offset look at the code below -

       Display display = getWindowManager().getDefaultDisplay();

       Drawable droid = ContextCompat.getDrawable(this, R.drawable.ic_abacus);

       Rect droidTarget = new Rect(0, 0, droid.getIntrinsicWidth() * 2, droid.getIntrinsicHeight() * 2);

        droidTarget.offset(display.getWidth(), display.getHeight());

       TapTargetSequence sequence = new TapTargetSequence(this)
                .targets(

                        TapTarget.forBounds(droidTarget,
                                "Oh look!",
                                "You can point to any part of the screen. You also can't cancel this one!")
                                .cancelable(false)
                                .dimColor(android.R.color.black)
                                .icon(droid)
                                .id(1)
                )
                .listener(new TapTargetSequence.Listener() {

                    @Override
                    public void onSequenceFinish() {

                        sequence.cancel();
                    }

                    @Override
                    public void onSequenceStep(TapTarget lastTarget, boolean targetClicked) {
                        
                    }

                    @Override
                    public void onSequenceCanceled(TapTarget lastTarget) {

                    }
                });

        sequence.start();

**Comment by xiphirx** [comment]
I dont know what you mean, you need to provide a lot more information.
