### ISSUE TITLE
Unable to stop a sequence

### ISSUE THREAD

**Issue by lb-sherpa** [KeepSafe/TapTargetView#276]
- [x ] I have verified the issue exists on the latest version
- [ x] I am able to reproduce it

**Version used: 1.11.0**

**Android version: 8.1**

Pseudocode:

seq = forSequence(tapTarget1.cancelable(false), tapTarget2.cancelable(false));
seq.start();

onBackPressed {
  // Change UI layout that the tap targets are not visible on the screen,
  // so the sequence becomes irrelevant.
  seq.cancel(); // DOES NOT STOP THE SEQUENCE only because tap targets are not cancelable!!!
}

**Comment by xiphirx** [comment]
This is intended, and documented behavior.
