### ISSUE TITLE
How to implement TapTargetView for NavigationDrawer view items ?

### ISSUE THREAD

**Issue by BharadwajaReddy** [KeepSafe/TapTargetView#277]
- [x] I have verified the issue exists on the latest version
- [ ] I am able to reproduce it

**Version used:**

**Stack trace:**

**Android version:**

**Comment by BharadwajaReddy** [comment]
This is not an issue. But i want to know weather this library supports tap target view for individual items  in Navigation Drawer.

**Comment by CalvinKern** [comment]
This was already answered here: https://github.com/KeepSafe/TapTargetView/issues/252

TL;DR: You can but you can't use menu items directly. You have to find the actual views from the drawer to be able to use them as a target.

**Comment by priyakar** [comment]
@BharadwajaReddy Hey, I was wondering if you were able to get this working? I dont have much reflection experience so would really appreciate it if you could walk me through it

**Comment by gcantoni** [comment]
> @BharadwajaReddy Hey, I was wondering if you were able to get this working? I dont have much reflection experience so would really appreciate it if you could walk me through it

see this https://github.com/KeepSafe/TapTargetView/issues/252#issuecomment-450574527
