### ISSUE TITLE
Option for transparent target circle

### ISSUE THREAD

**Issue by lpellegr** [KeepSafe/TapTargetView#28]
Let's say you want to use the TapTargetView with the 3 dots settings icon (overflow icon) that is available in the toolbar of some apps on top right side. Since there is no resource ID associated to this icon, using `TapTarget.forBounds` is the only way to target this icon. Unfortunately, the target circle cannot be transparent, thus hidding the icon when TapTargetView is used. 

It would be nice to have an option for having a transparent target circle. Probably, using `transparentPaint.setXfermode(new PorterDuffXfermode(PorterDuff.Mode.CLEAR))` with the `Paint` object instance when the option is enabled.

**Comment by xiphirx** [comment]
You can solve this also by using `.icon(Drawable)` and specifying the 3 dot drawable, does this suffice?

**Comment by lpellegr** [comment]
Yes, thank you.

**Comment by ansgarm** [comment]
I'd also appreciate a transparency option for the target color. In my case it is a custom view for which I've got no drawables to use. Right now I'm using a screenshot as a workaround, but it would be nice to be able to show the actual view.

**Comment by xiphirx** [comment]
432485bc29d27afaa40babe49af5f4d2f753148c Enjoy. Please use a snapshot if you need this functionality immediately

**Comment by ansgarm** [comment]
Just wow. That was quick. Thank you!
