### ISSUE TITLE
Is there "Got it" button support for this library. It will be so good , if this thing is there. Can anybody tell answer me.

### ISSUE THREAD

**Issue by BharadwajaReddy** [KeepSafe/TapTargetView#280]
- [x] I have verified the issue exists on the latest version
- [ ] I am able to reproduce it

**Version used:**

**Stack trace:**

**Android version:**

**Comment by BharadwajaReddy** [comment]
Some other applications using some showcase library are having this feature.

**Comment by xiphirx** [comment]
This doesn't conform to the material design guidelines, so no.
