### ISSUE TITLE
Customize outer circle's center and radius

### ISSUE THREAD

**Issue by densvr** [KeepSafe/TapTargetView#282]
Please provide a feature to customize outer circle's center and radius
It is easy to do with making the following methods protected
1. `TapTargetView.getOuterCircleRadius`
2. `TapTargetView.getOuterCircleCenterPoint`

**Comment by xiphirx** [comment]
The guidelines are pretty specific on how the positioning works. Since this library aims to follow the guidelines, this is outside of the scope of the library, sorry.

**Comment by Rolf-Smit** [comment]
@xiphirx could you reconsider this? In some cases it makes allot of sense to have a bigger circle, such as in this example with this wide button. Or at least an option to add a bit more margin between the outer circle and the button?
![MicrosoftTeams-image (7)](https://user-images.githubusercontent.com/6614322/86922305-b5245380-c12c-11ea-8e96-c508f337a6a2.png)
