### ISSUE TITLE
On cancelling targetview, background screen is getting blocked.

### ISSUE THREAD

**Issue by NeerajaReddyKomma** [KeepSafe/TapTargetView#285]
- [x] I have verified the issue exists on the latest version
- [x] I am able to reproduce it

**Version used:** 1.11.0

**Stack trace:**  On cancelling targetview, Background view is blocked unable to do any other action on that.

**Android version:** 6.0.1

**Comment by jitarun** [comment]
I'm also facing same issue, any updates?.

**Comment by NeerajaReddyKomma** [comment]
@jitarun  No.. Waiting for author to figure what might be solution.

**Comment by bellierjonathan** [comment]
<img width="409" alt="capture d ecran 2018-06-14 a 15 38 36" src="https://user-images.githubusercontent.com/5746542/41415540-16c2a0e8-6fe9-11e8-83e3-dd5804e1653f.png">

When my background is blocked, I still have the view on the top 😶 but nothing is visible.

**Comment by canouser** [comment]
same issue i am also facing ...

**Comment by xiphirx** [comment]
Do you have a case that reproduces this issue? I'm not sure what would be going wrong here. At the very least, you should be able to remove that view yourself.

**Comment by NeerajaReddyKomma** [comment]
As soon as we tap on target view, screen gets blocked i mean untouchable. So we can't perform any further actions. Either we should close app and reopen it or we should finish and recreate activity.

**Comment by JandemX** [comment]
Not enough Info but:  can it be that you overwrite the onTargeClick Listener Method? If so, then the isInteractable Boolean is set false and never set true agein, all further onClick actions get ignored.

**Comment by xiphirx** [comment]
It seems like `onTargetClick` is being overridden and the overridden implementation is not calling `super`, and so the view is never dismissed. If you are going to override `onTargetClick` then you need to ensure you dismiss the view.

Closing now, if there is new info or if this is not the case then please open a new issue.
