### ISSUE TITLE
HI,  How can we implement it on bottom navigation view.    when i try to implement it shoes blank space with fill of a color,

### ISSUE THREAD

**Issue by Ankitinstantpay** [KeepSafe/TapTargetView#287]
- [ ] I have verified the issue exists on the latest version
- [ ] I am able to reproduce it

**Version used:**

**Stack trace:**

**Android version:**

![device-2018-04-17-155347](https://user-images.githubusercontent.com/25837097/38864280-df415650-4257-11e8-868e-49c964066d6a.png)

**Comment by xiphirx** [comment]
Try using a transparent target. `.transparentTarget(true)`
