### ISSUE TITLE
TapTagetView not showing in release build

### ISSUE THREAD

**Issue by burhankhanzada199888** [KeepSafe/TapTargetView#288]
- [x] I have verified the issue exists on the latest version
- [x] I am able to reproduce it

**Version used:**
1.11.0

**Stack trace:**

**Android version:**
6.0.1

please provide progruard rules for release build of your library

**Comment by burhankhanzada199888** [comment]
please provide progruard rules for release build of your library

**Comment by xiphirx** [comment]
This library is small enough that you should just ignore it in your proguard settings.
