### ISSUE TITLE
How do I make the target view to show only when the activity is opened for the first time. There must be a method to control this. For eg ---> showOnce() 

### ISSUE THREAD

**Issue by annshsingh** [KeepSafe/TapTargetView#289]
- [*] I have verified the issue exists on the latest version
- [*] I am able to reproduce it

**Comment by annshsingh** [comment]
I am using sharedPreferences to handle the visibility for basic app intro views that are to be shown just once until the app is reinstalled.

**Comment by xiphirx** [comment]
This is outside of the scope of the library, you can just store a simple boolean in `SharedPreferences` or something else.
