### ISSUE TITLE
TapTargetSequence and single cancellable TapTarget

### ISSUE THREAD

**Issue by francescogatto** [KeepSafe/TapTargetView#290]
I'd like to mix cancellable and not cancellable TapTarget in the TapTargetSequence, because for example i want to evidence a TextView and in other step a button. 
But when I tap on a cancellable Target, the TapTargetSequence is interrupted. 
Anyone know how to resolve this? 

Thanks

**Comment by xiphirx** [comment]
It sounds like you want `continueOnCancel`
