### ISSUE TITLE
Please allow cancelable to cancel "anywhere" even "on" outer circle

### ISSUE THREAD

**Issue by Noitidart** [KeepSafe/TapTargetView#293]
This is a feature request. I am using the react-native bridge - https://github.com/prscX/react-native-app-tour/issues/13#issuecomment-393481330

Please allow "cancelable" to make touch "anywhere on screen" cancel it. I am trying to cancel by pressing on the "outer circle". My outer circle is very big so there is no area around it. So the only place that is canceling right now is touching inside the tiny inner circle.

**Comment by xiphirx** [comment]
You can attach a `TapTargetView.Listener` to your `TapTargetView` and override `onOuterCircleClick` to get the behavior you want.

**Comment by Noitidart** [comment]
Thank you very much @xiphirx for fast reply!

**Comment by prscX** [comment]
Thanks @xiphirx for the quick response and sharing the API reference.

Based on your suggestion, I have make the required changes in the wrapper library.

Thanks
</ Pranav >
