### ISSUE TITLE
how to add a skip button on taptargetview for cancel the session,because after start a taptargetview it not allow to touch at any other view of xml, but i need to allow a touch on skip button ,which present in my xml activity,android

### ISSUE THREAD

**Issue by canouser** [KeepSafe/TapTargetView#295]
- [x] I have verified the issue exists on the latest version
- [x] I am able to reproduce it

**Version used:**

**Stack trace:**

**Android version:**

**Comment by xiphirx** [comment]
This isn't supported and isn't how the library is supposed to be used. You should instead treat a cancel as a skip.

**Comment by saddahussain** [comment]
what a shame.
