### ISSUE TITLE
LG G6 "Hide Home Touch Buttons" feature cuts off bottom of view

### ISSUE THREAD

**Issue by Kirimaru** [KeepSafe/TapTargetView#304]
- [X] I have verified the issue exists on the latest version
- [X] I am able to reproduce it

**Version used:** 1.12.0

**Stack trace:** LG G6 "Hide Home Touch Buttons" feature causes bottom of TapTargetView to be cut off. 
Image attached.
<img width="288" alt="lg_g6_tooltip_issue" src="https://user-images.githubusercontent.com/18707958/43602750-b7a37bea-9645-11e8-85dc-b6a53387e271.png">
Note: Target is bottom right view.

**Android version:** 8.0.0

**Comment by mickele** [comment]
This issue is also happening on a S8 with the feature "Show and hide button" enabled.
Basically the same feature as LG's to hide nav buttons by default and swiping up to show them.
