### ISSUE TITLE
Xfer mode change in Android P

### ISSUE THREAD

**Issue by hearsilent** [KeepSafe/TapTargetView#313]
- [x] I have verified the issue exists on the latest version
- [x] I am able to reproduce it

**Version used:** 1.12.0

**Stack trace:**
In support library 28.0.0, start of anim will have a rect.

### 27.1.1
<img width="570" src="https://user-images.githubusercontent.com/5742579/46189627-14332280-c322-11e8-9653-81011922fd4e.png">  
<img width="320"  src="https://user-images.githubusercontent.com/5742579/46189594-f1a10980-c321-11e8-8a14-a1d126b682ec.gif"> 

### 28.0.0
<img width="570" src="https://user-images.githubusercontent.com/5742579/46189637-21501180-c322-11e8-866f-fa7669e5ff11.png">  
<img width="320"  src="https://user-images.githubusercontent.com/5742579/46189605-fcf43500-c321-11e8-8416-b7934a26c95d.gif"> 

**Android version:** 9.0

**Comment by xiphirx** [comment]
Does this still occur after the Android X migration that was just committed? I'm confused as to why the support library would change how the Canvas operates... Are you sure this isnt an Android P issue?

**Comment by hearsilent** [comment]
@xiphirx You can see this issue: https://issuetracker.google.com/issues/111819103
Google says won't fix :'(

**Comment by hearsilent** [comment]
In pre 19 devices method is tricky.
I `clipPath` but circle is jagged, so need to draw a 1px border circle to fix jagged.

You can see this method in [uCrop](https://github.com/Yalantis/uCrop/blob/master/ucrop/src/main/java/com/yalantis/ucrop/view/OverlayView.java#L443-L462).
