### ISSUE TITLE
TargetView not overlap on view

### ISSUE THREAD

**Issue by Slake07** [KeepSafe/TapTargetView#328]
i am using 1.12.0 version of this library and android version is 7.0.
Below is issue i am facing.
![device-2018-12-07-132305](https://user-images.githubusercontent.com/3199539/49634758-b149c000-fa23-11e8-845a-e2928822f3c8.png)

SIGN IN button should overlap with taptargetview.

**Comment by xiphirx** [comment]
Use `.transparentTarget(true)`

**Comment by Slake07** [comment]
I already did that. see below code:

TapTarget.forView(rootView.tvUnlockIncBottomHomeNowRideEst, "Title","You can start ride from here")
                        .dimColor(R.color.text_color_black)
                        .outerCircleColor(R.color.warm_grey)
                        .targetCircleColor(R.color.text_color_black)
                        .targetRadius(100)
                        .transparentTarget(true)

**Comment by xiphirx** [comment]
Then your button's view's index is larger than the `TapTargetView` in your root content view's `FrameLayout`. Is `tvUnlockIncBottomHomeNowRideEst` referring to the "SIGN IN" button?

**Comment by Slake07** [comment]
<?xml version="1.0" encoding="utf-8"?>

<android.support.constraint.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:shimmer="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="@dimen/bottom_home_box_height"
    android:background="@color/white"
    android:clipToPadding="false">

    <android.support.constraint.ConstraintLayout
        android:id="@+id/clTopBottomHomeNowRideEst"
        android:layout_width="match_parent"
        android:layout_height="0dp"
        android:background="@color/white"
        android:clipToPadding="false"
        app:layout_constraintHeight_default="percent"
        app:layout_constraintHeight_percent="0.5">

        <com.facebook.shimmer.ShimmerFrameLayout
            android:id="@+id/shimmer_view_container"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:layout_gravity="center"
            android:orientation="vertical"

            shimmer:duration="800">

            <include layout="@layout/bottom_home_now_ride_shimmer_view" />
        </com.facebook.shimmer.ShimmerFrameLayout>

        <RelativeLayout
            android:id="@+id/rvBikeSelBottomHomeNowRideEst"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:gravity="center_vertical"
            android:paddingLeft="@dimen/bottom_home_rvbike_padding_left"
            android:paddingRight="@dimen/bottom_home_rvbike_padding_right"
            android:visibility="gone">

            <e.smart.leap.ui.custom.CircleImageView
                android:id="@+id/civVehicleBottomHomeNowRideEst"
                android:layout_width="@dimen/bottom_home_now_bike_pic_size"
                android:layout_height="@dimen/bottom_home_now_bike_pic_size"
                android:layout_alignParentLeft="true"
                app:civ_border_color="@color/image_border_color"
                android:layout_marginTop="@dimen/dim_5_dp"
                app:civ_border_width="@dimen/dim_2_dp"
                app:srcCompat="@drawable/ic_bike_placeholder" />


            <android.support.v7.widget.AppCompatTextView
                android:id="@+id/tvVehicleNameBottomHomeNowRideEst"
                style="@style/LargeFont.Black"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_marginLeft="@dimen/bottom_home_now_tvvehicle_margin_left"
                android:layout_toLeftOf="@+id/llLeapDetailsBottomHomeNowRideEst"
                android:layout_toRightOf="@+id/civVehicleBottomHomeNowRideEst"
                android:ellipsize="end"
                android:lines="1"
                app:fontFamily="@font/com_regular" />

            <LinearLayout
                android:id="@+id/llLeapDetailsBottomHomeNowRideEst"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_alignParentRight="true"
                android:layout_marginTop="@dimen/dim_5_dp"
                android:gravity="right"
                android:orientation="horizontal">

                <android.support.constraint.ConstraintLayout
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content">

                    <com.facebook.shimmer.ShimmerFrameLayout
                        android:id="@+id/shimmer_view_containerEstimate"
                        android:layout_width="match_parent"
                        android:layout_height="match_parent"
                        android:layout_gravity="center"
                        android:orientation="vertical"
                        shimmer:duration="800">

                        <android.support.v7.widget.AppCompatTextView
                            style="@style/SmallFont.Black"
                            android:layout_width="@dimen/shimmer_now_vh_bat_placeholder_text_width"
                            android:layout_height="wrap_content"
                            android:background="@color/shimmer_placeholder_bg"
                            app:fontFamily="@font/maven_regular" />

                    </com.facebook.shimmer.ShimmerFrameLayout>

                    <LinearLayout
                        android:id="@+id/llLeapEstimateBottomHomeNowRideEst"
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:gravity="center_horizontal"
                        android:visibility="invisible"
                        android:orientation="horizontal">

                        <android.support.v7.widget.AppCompatImageView
                            android:layout_width="@dimen/dim_20_dp"
                            android:layout_height="@dimen/dim_20_dp"
                            app:srcCompat="@drawable/ic_distance" />

                        <android.support.v7.widget.AppCompatTextView
                            android:id="@+id/tvLeapEstimateBottomHomeNowRideEst"
                            style="@style/SmallFont.Black"
                            android:layout_marginLeft="@dimen/dim_5_dp"
                            android:layout_width="wrap_content"
                            android:layout_height="wrap_content"
                            app:fontFamily="@font/maven_regular" />
                    </LinearLayout>

                </android.support.constraint.ConstraintLayout>

            </LinearLayout>

            <android.support.v7.widget.AppCompatTextView
                android:id="@+id/tvBatteryLblBottomHomeNowRideEst"
                style="@style/LargeFont.Green"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_below="@+id/tvVehicleNameBottomHomeNowRideEst"
                android:layout_marginLeft="@dimen/bottom_home_now_tvvehicle_margin_left"
                android:layout_toRightOf="@+id/civVehicleBottomHomeNowRideEst"
                android:text="@string/battery_"
                app:fontFamily="@font/maven_regular" />

            <android.support.v7.widget.AppCompatTextView
                android:id="@+id/tvBatteryBottomHomeNowRideEst"
                style="@style/LargeFont.Black"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_below="@+id/tvVehicleNameBottomHomeNowRideEst"
                android:layout_toRightOf="@+id/tvBatteryLblBottomHomeNowRideEst"
                app:fontFamily="@font/maven_regular" />

            <LinearLayout
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_alignParentRight="true"
                android:layout_below="@+id/tvVehicleNameBottomHomeNowRideEst"
                android:layout_toRightOf="@+id/tvBatteryBottomHomeNowRideEst"
                android:gravity="right"
                android:orientation="horizontal">

                <android.support.v7.widget.AppCompatTextView
                    android:id="@+id/tvRangeLblBottomHomeNowRideEst"
                    style="@style/LargeFont.Green"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:text="@string/range_"
                    app:fontFamily="@font/maven_regular" />

                <android.support.v7.widget.AppCompatTextView
                    android:id="@+id/tvRangeBottomHomeNowRideEst"
                    style="@style/LargeFont.Black"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    app:fontFamily="@font/maven_regular" />
            </LinearLayout>
        </RelativeLayout>
    </android.support.constraint.ConstraintLayout>

    <android.support.v7.widget.AppCompatTextView
        android:id="@+id/tvUnlockIncBottomHomeNowRideEst"
        style="@style/MediumFont.White"
        android:layout_width="match_parent"
        android:layout_height="0dp"
        android:background="@drawable/go_button_flat_back"
        android:foreground="?android:attr/selectableItemBackground"
        android:gravity="center"
        app:fontFamily="@font/maven_med"
        app:layout_constraintHeight_default="percent"
        app:layout_constraintHeight_percent="0.5"
        app:layout_constraintTop_toBottomOf="@+id/clTopBottomHomeNowRideEst" />

</android.support.constraint.ConstraintLayout>
