### ISSUE TITLE
TargetView not overlap on view

### ISSUE THREAD

**Issue by Slake07** [KeepSafe/TapTargetView#329]
#328 i already did as you (@xiphirx )said in this issue. see below code:

TapTarget.forView(rootView.tvUnlockIncBottomHomeNowRideEst, "Title","You can start ride from here")
.dimColor(R.color.text_color_black)
.outerCircleColor(R.color.warm_grey)
.targetCircleColor(R.color.text_color_black)
.targetRadius(100)
.transparentTarget(true)

**Comment by xiphirx** [comment]
Dont create new issues for the same thing.
