### ISSUE TITLE
TapTargetView cut off on devices with cutout/notch

### ISSUE THREAD

**Issue by svenjacobs** [KeepSafe/TapTargetView#333]
- [✓] I have verified the issue exists on the latest version
- [✓] I am able to reproduce it

**Version used:**
1.12.0

**Stack trace:**
not available

**Android version:**
Google Pixel 3 XL, 9.0
One Plus 6, OxygenOS 9.0.3

It seems that `TapTargetView` has an issue with devices with a cutout/notch. The view is cut off at the bottom with a height that seems to be the height of the cutout. Here are screenshots from a Google Pixel 3 XL and a One Plus 6. The cutout of the One Plus 6 is smaller and so is the area that is cut off from the view. The view works fine on devices without a cutout like the Pixel (1) and Pixel 3.

![screenshot_20190204-095339](https://user-images.githubusercontent.com/255313/52198923-c648a100-2864-11e9-800e-31cf4cce6990.png)

![screenshot_20190204-095335](https://user-images.githubusercontent.com/255313/52198928-cc3e8200-2864-11e9-8772-b6126a1a6549.jpg)

**Comment by svenjacobs** [comment]
The snapshot release doesn't have this error. Probably due to fix #311.
Can you please create a new release version?

**Comment by debajyotibasak** [comment]
* [✓] I have verified the issue exists on the latest version

    * [✓] I am able to reproduce it


**Version used:**
1.12.0

**Stack trace:**
not available

**Android version:**
One Plus 6, OxygenOS 9.0.3

This is occuring in the One Plus 6 Device especially for the notch. 
 
![screenshot_20190218-115245 01](https://user-images.githubusercontent.com/16916934/52931987-5feb7480-3374-11e9-97c0-e82590023c8a.jpg)

**Comment by mauriciolima88** [comment]
Any solution? I debug on a Motorola One which has a notch and also show a cut off.

**Comment by svenjacobs** [comment]
As I wrote earlier the snapshot version already contains a fix for this bug. Still waiting for a new release.

**Comment by Etinka** [comment]
Do we know when a new release is due? This is a huge issue for us...

**Comment by androideveloper** [comment]
We thought it was related to Android 9..Thanks for sharing!

**Comment by svenjacobs** [comment]
@philippb This has been [fixed](https://github.com/KeepSafe/TapTargetView/pull/311) almost a year ago in the snapshot version. Please finally create a new release 🙏

**Comment by svenjacobs** [comment]
Has been fixed in release 1.13.0

**Comment by LeroyStaines** [comment]
Having this issue with the top notch on a Samsung Galaxy S20.

Version 1.13.0
