### ISSUE TITLE
New release 

### ISSUE THREAD

**Issue by snpefk** [KeepSafe/TapTargetView#340]
Hello. 

Can you please release new version of the lib? I'm particularly in need of the b413c08e1170b81f02c10fa5f8a1b4bfbdf56d82 commt.

**Comment by snpefk** [comment]
bump @philippb

**Comment by svenjacobs** [comment]
I'm also [waiting](https://github.com/KeepSafe/TapTargetView/issues/333) for a new release of the library since beginning of this year. I think this library is dead 😢

**Comment by philippb** [comment]
Very sorry I didn’t see this. Let us take care of this. We still use it on
production.

**Comment by philippb** [comment]
@snpefk I just released version 1.13.0 from `master`.
Sorry this took so long!

Also I @tomasz-keepsafe, one of our senior Android engineers to be the new maintainer for this project.

**Comment by svenjacobs** [comment]
It seems version 1.13.0 has not yet been published to JCenter/Maven?
