### ISSUE TITLE
Gap at the bottom when you use On Screen Buttons

### ISSUE THREAD

**Issue by zdunex25** [KeepSafe/TapTargetView#352]
- [x] I have verified the issue exists on the latest version
- [x] I am able to reproduce it

**Version used:**
1.12.0

**Stack trace:**
not available

**Android version:**
9.0

This is what happens on Xiaomi MI8SE, no such issue on MI6 (with hardware buttons):
![2019-05-21 (1)](https://user-images.githubusercontent.com/1674725/58114762-bdec5a00-7bf8-11e9-83bc-35de91b362f6.png)

**Comment by Gamis214** [comment]
I have the same issue :( in emulator work fine but in the device happen that...

**Comment by Uni2K** [comment]
Same problem on Galaxy S10.

**Comment by henrichg** [comment]
This is already fixed. Use snapshot of this library: 

`implementation 'com.github.KeepSafe:TapTargetView:master-SNAPSHOT'`

**Comment by rishabh876** [comment]
When is this new version releasing? @henrichg

**Comment by henrichg** [comment]
I do not known. Ask author.

**Comment by svenjacobs** [comment]
Probably related to #333

**Comment by tomasz-keepsafe** [comment]
This bug was fixed in https://github.com/KeepSafe/TapTargetView/pull/311 and included in latest release 1.13.
