### ISSUE TITLE
problem with bottom view

### ISSUE THREAD

**Issue by mohtasham1988** [KeepSafe/TapTargetView#359]
**how can I fix it?**
I have this problem on A20 and A50 Samsung
  taptargetview:1.12.0'

![a](https://user-images.githubusercontent.com/22011648/63686854-41c96a00-c818-11e9-90d8-18a3569d569b.png)

**Comment by svenjacobs** [comment]
Probably related to #333. Has the device a cutout?

**Comment by tomasz-keepsafe** [comment]
This bug was fixed in https://github.com/KeepSafe/TapTargetView/pull/311 and included in latest release 1.13.
