### ISSUE TITLE
For Display Swipable Area

### ISSUE THREAD

**Issue by patelakshay13890** [KeepSafe/TapTargetView#36]
how to show anim for SwipableLeft or SwipableRight area ??
i.e. like opening Drawer & for the Pull to refresh events

**Comment by xiphirx** [comment]
I'm sorry, I can't exactly understand what you're asking. Are you asking how to use the the library for an item inside of a navigation drawer?

**Comment by patelakshay13890** [comment]
No buddy, I want to show Swip like animation for NavigationDrawer on Both Side Left & Right..
And I want to show help for Pull To Refresh for RecyclerView....

**Comment by xiphirx** [comment]
I see. Unfortunately, this library is only for taps, not swipes. It seems like you would need something else to do that for you.

For reference, this library is trying to adhere to the guidelines put into place [here](https://material.google.com/growth-communications/feature-discovery.html).

**Comment by patelakshay13890** [comment]
Okay  ,  thanks  for  your  reply
