### ISSUE TITLE
ERROR: Failed to resolve: com.getkeepsafe.taptargetview:taptargetview:1.13.0

### ISSUE THREAD

**Issue by ziem** [KeepSafe/TapTargetView#363]
- [x] I have verified the issue exists on the latest version
- [x] I am able to reproduce it

**Version used:**
1.13.0

**Stack trace:**

>ERROR: Failed to resolve: com.getkeepsafe.taptargetview:taptargetview:1.13.0

I'm trying to update TapTargetView from 1.12.0 to 1.13.0 but it seems that the newest version is missing *.pom file which may cause the error above. https://bintray.com/keepsafesoftware/Android/TapTargetView/1.13.0#files/com%2Fgetkeepsafe%2Ftaptargetview%2Ftaptargetview%2F1.13.0 shows only:

- taptargetview-1.13.0-javadoc.jar
- taptargetview-1.13.0-sources.jar
- taptargetview-1.13.0.aar

where the old version https://bintray.com/keepsafesoftware/Android/TapTargetView/1.12.0#files/com%2Fgetkeepsafe%2Ftaptargetview%2Ftaptargetview%2F1.12.0 has:

- taptargetview-1.12.0-javadoc.jar
- taptargetview-1.12.0-sources.jar
- taptargetview-1.12.0.aar
- taptargetview-1.12.0.pom

**Comment by philippb** [comment]
We're looking into why the POM file was not created.

**Comment by emarc-m** [comment]
@ziem 
Could you please try pulling the dependencies again? All files should now be visible in [jCenter](https://bintray.com/keepsafesoftware/Android/TapTargetView/1.13.0?sort=&order=#files/com%2Fgetkeepsafe%2Ftaptargetview%2Ftaptargetview%2F1.13.0). Thank you.

**Comment by svenjacobs** [comment]
Download is now working!

**Comment by ziem** [comment]
It works now! 🎉  Thanks for the quick fix 👍

**Comment by tomasz-keepsafe** [comment]
Version 1.13 should now be available from gradle.
I confirmed that gradle dependency is working:
`implementation 'com.getkeepsafe.taptargetview:taptargetview:1.13.0'`

**Comment by KalyaniDigiwill** [comment]
how can i use this inside fragment. I am facing issue, after finishing sequence,app not working it is stuck. not scrolling.
