### ISSUE TITLE
JCenter distribution

### ISSUE THREAD

**Issue by hannesvoss** [KeepSafe/TapTargetView#384]
[Starting from May 1, 2021 JCenter will stop working.](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/) Are there any plans on migrating to another distribution service?
I would love to be able to continue using the project.

**Comment by kenyee** [comment]
ditto...project should be forked if not

**Comment by mshandrovskiy** [comment]
Ping @emarc-m
