### ISSUE TITLE
findViewById(R.id.target) not working

### ISSUE THREAD

**Issue by keithchad** [KeepSafe/TapTargetView#386]
- [x] I have verified the issue exists on the latest version
- [x] I am able to reproduce it

**Version used:1.13.2**

**Stack trace:**

**Android version:30**

**Issue** 
Hello. I have a small issue.
the findViewById(R.id.target) does not work.This is my first time using the library so I do not know where the problem is.Kindly Help me.

**Screenshot attached below:**
![Screenshot from 2021-03-24 21-03-13](https://user-images.githubusercontent.com/63049827/112362255-4ea88b00-8ce5-11eb-95a4-075a62c25f99.png)

**Comment by angatha** [comment]
Hi @keithchad, I guess `HomeFragmentPatient` is a Fragment. This class doesn't have a `findViewById(int)` method and this is causing your problem. (Needless to say it has nothing to do with this library.)

As far as I know, in an activity you have this method with is more or less a delegate to `View#findViewById(int)` of the root view of the activity. The method searches for a child of the view with the specified id. So in a fragment, most likely you wanted to do something like `requireView().findViewById(R.id.textHeartbeat)`. 

This searches for the textHeartbeat view in the views related to the fragment.
