### ISSUE TITLE
Setting text size for custom typeface ( question )

### ISSUE THREAD

**Issue by IRMobydick** [KeepSafe/TapTargetView#40]
Hi there,
Is it possible to set text size for title and description separately?!
You know what, in some cases when you set typeface to text, it seems too big!! and need to reduce text size to get better result!

Or can set two different typeface for title and description?

Thanks :)

**Comment by xiphirx** [comment]
Do you have an example of where the text is too big because of a custom typeface?

Currently you cannot set the size of the text.

**Comment by IRMobydick** [comment]
![screenshot_2016-10-09-00-57-32](https://cloud.githubusercontent.com/assets/4468890/19218356/a6a0ecec-8e04-11e6-8e3f-f334e507c911.png)

As you can see in picture, `TapTargetView` text in compare with other elements, seems too big

**Comment by xiphirx** [comment]
Have you tried https://developer.android.com/reference/android/text/style/RelativeSizeSpan.html ? Does this work for your situation? 

Checking the Material Design guidelines again, I don't see an explicit text size defined... so I suppose this should be supported.

Thanks for the screenshot. I'll be adding this soon; of course, as always, a PR is welcome.

**Comment by xiphirx** [comment]
If you need this functionality immediately, please use a snapshot

**Comment by IRMobydick** [comment]
Thank you bro! 👍
