### ISSUE TITLE
The TapTarget does not fit properly after rotation

### ISSUE THREAD

**Issue by ZetDeveloper** [KeepSafe/TapTargetView#41]
The TapTarget does not fit properly after rotation, In landscape mode the taptarget should be in the settings icon

![screenshot_2016-10-08-23-56-27](https://cloud.githubusercontent.com/assets/12779016/19218051/85bdd202-8db3-11e6-9fef-fce07a137fb6.png)
![screenshot_2016-10-08-23-56-40](https://cloud.githubusercontent.com/assets/12779016/19218052/85d664f2-8db3-11e6-8d36-e3178b8089fd.png)

![screenshot_2016-10-09-00-03-08](https://cloud.githubusercontent.com/assets/12779016/19218057/233bed48-8db4-11e6-90d8-3a20a44a2b59.png)
![screenshot_2016-10-09-00-03-18](https://cloud.githubusercontent.com/assets/12779016/19218058/235769d8-8db4-11e6-90c9-c7231919d452.png)

- [x] I have verified the issue exists on the latest version
- [x] I am able to reproduce it

**Version used:**

**Stack trace:**

**Android version:**

**Comment by xiphirx** [comment]
How are you displaying the TapTargetView?

**Comment by ZetDeveloper** [comment]
this is mi code 

`  final SpannableString sassyDesc = new SpannableString("It allows you to go back, sometimes");
            sassyDesc.setSpan(new StyleSpan(Typeface.ITALIC), sassyDesc.length() - "somtimes".length(), sassyDesc.length(), 0);
            


            TapTargetView tapTargetView = TapTargetView.showFor(this, TapTarget.forToolbarMenuItem(toolbar, R.id.menuGuardar, "This is a search icon", "As you can see, it has gotten pretty dark around here...")
                            .dimColor(android.R.color.black)
                            .outerCircleColor(R.color.colorAccent)
                            .targetCircleColor(android.R.color.black)
                            .textColor(android.R.color.black)
                            .cancelable(false),                   
                    new TapTargetView.Listener() {          /
                        @Override
                        public void onTargetClick(TapTargetView view) {
                            super.onTargetClick(view);      // This call is optional
                           view.dismiss(true);
                            toolbar.inflateMenu(R.menu.menu_login);
                        }
                    });
`

**Comment by ZetDeveloper** [comment]
this is my code

`   final SpannableString sassyDesc = new SpannableString("It allows you to go back, sometimes");
            sassyDesc.setSpan(new StyleSpan(Typeface.ITALIC), sassyDesc.length() - "somtimes".length(), sassyDesc.length(), 0);



            TapTargetView tapTargetView = TapTargetView.showFor(this, TapTarget.forToolbarMenuItem(toolbar, R.id.menuGuardar, "This is a search icon", "As you can see, it has gotten pretty dark around here...")
                            .dimColor(android.R.color.black)
                            .outerCircleColor(R.color.colorAccent)
                            .targetCircleColor(android.R.color.black)
                            .textColor(android.R.color.black)
                            .cancelable(false),
                    new TapTargetView.Listener() {          
                        @Override
                        public void onTargetClick(TapTargetView view) {
                            super.onTargetClick(view);    
                           view.dismiss(true);
                            toolbar.inflateMenu(R.menu.menu_login);
                        }
                    });`

**Comment by ZetDeveloper** [comment]
this is my codee

`   final SpannableString sassyDesc = new SpannableString("It allows you to go back, sometimes");
            sassyDesc.setSpan(new StyleSpan(Typeface.ITALIC), sassyDesc.length() - "somtimes".length(), sassyDesc.length(), 0);



            TapTargetView tapTargetView = TapTargetView.showFor(this, TapTarget.forToolbarMenuItem(toolbar, R.id.menuGuardar, "This is a search icon", "As you can see, it has gotten pretty dark around here...")
                            .dimColor(android.R.color.black)
                            .outerCircleColor(R.color.colorAccent)
                            .targetCircleColor(android.R.color.black)
                            .textColor(android.R.color.black)
                            .cancelable(false),
                    new TapTargetView.Listener() {          
                        @Override
                        public void onTargetClick(TapTargetView view) {
                            super.onTargetClick(view);    
                           view.dismiss(true);
                            toolbar.inflateMenu(R.menu.menu_login);
                        }
                    });`

**Comment by ZetDeveloper** [comment]
this is my code

`  TapTargetView tapTargetView = TapTargetView.showFor(this, TapTarget.forToolbarMenuItem(toolbar, R.id.menuGuardar, "This is a search icon", "As you can see, it has gotten pretty dark around here...")
                            .dimColor(android.R.color.black)
                            .outerCircleColor(R.color.colorAccent)
                            .targetCircleColor(android.R.color.black)
                            .textColor(android.R.color.black)
                            .cancelable(false),                 
                    new TapTargetView.Listener() {        
                        @Override
                        public void onTargetClick(TapTargetView view) {
                            super.onTargetClick(view);     
                           view.dismiss(true);
                            toolbar.inflateMenu(R.menu.menu_login);
                        }
                    });`

**Comment by ZetDeveloper** [comment]
` TapTargetView tapTargetView = TapTargetView.showFor(this, TapTarget.forToolbarMenuItem(toolbar, R.id.menuGuardar, "This is a search icon", "As you can see, it has gotten pretty dark around here...")
                            .dimColor(android.R.color.black)
                            .outerCircleColor(R.color.colorAccent)
                            .targetCircleColor(android.R.color.black)
                            .textColor(android.R.color.black)
                            .cancelable(false),
                    new TapTargetView.Listener() {
                        @Override
                        public void onTargetClick(TapTargetView view) {
                            super.onTargetClick(view);
                            view.dismiss(true);
                            toolbar.inflateMenu(R.menu.menu_login);
                        }
                    });`

**Comment by ZetDeveloper** [comment]
this is my code

` TapTargetView tapTargetView = TapTargetView.showFor(this, TapTarget.forToolbarMenuItem(toolbar, R.id.menuGuardar, "This is a search icon", "As you can see, it has gotten pretty dark around here...")
                            .dimColor(android.R.color.black)
                            .outerCircleColor(R.color.colorAccent)
                            .targetCircleColor(android.R.color.black)
                            .textColor(android.R.color.black)
                            .cancelable(false),
                    new TapTargetView.Listener() {
                        @Override
                        public void onTargetClick(TapTargetView view) {
                            super.onTargetClick(view);
                            view.dismiss(true);
                            toolbar.inflateMenu(R.menu.menu_login);
                        }
                    });`

**Comment by ZetDeveloper** [comment]
TapTargetView tapTargetView = TapTargetView.showFor(this, TapTarget.forToolbarMenuItem(toolbar, R.id.menuGuardar, "This is a search icon", "As you can see, it has gotten pretty dark around here...")
                            .dimColor(android.R.color.black)
                            .outerCircleColor(R.color.colorAccent)
                            .targetCircleColor(android.R.color.black)
                            .textColor(android.R.color.black)
                            .cancelable(false),
                    new TapTargetView.Listener() {
                        @Override
                        public void onTargetClick(TapTargetView view) {
                            super.onTargetClick(view);
                            view.dismiss(true);
                            toolbar.inflateMenu(R.menu.menu_login);
                        }
                    });

**Comment by xiphirx** [comment]
Are you retaining the same `TapTargetView` across orientation changes?

**Comment by ZetDeveloper** [comment]
yes,  my code is within the method:  "protected void onCreate(Bundle savedInstanceState) {"

**Comment by xiphirx** [comment]
I cannot reproduce this. Please make sure you're creating your `TapTargetView` each time a configuration change occurs (dont save the instance) and that you're creating the view after you inflate your toolbar's menu.

Are you using `ActionBar` or `Toolbar` in your layout?

**Comment by ZetDeveloper** [comment]
in toolbar this is my code

`  @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        setContentView(R.layout.activity_main);
        ButterKnife.inject(this);



        realmConfiguration = new RealmConfiguration.Builder(this)
                .name(Realm.DEFAULT_REALM_NAME)
                .schemaVersion(0)
                .deleteRealmIfMigrationNeeded()
                .build();


        Realm.setDefaultConfiguration(realmConfiguration);

        realm = Realm.getInstance(realmConfiguration);

        mCache = ACache.get(this);

        final Toolbar toolbar = (Toolbar) findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);
        toolbar.setNavigationIcon(R.drawable.ic_remove_red_eye_white_24dp);
        toolbar.inflateMenu(R.menu.menu_login);

        try {



         final SpannableString sassyDesc = new SpannableString("It allows you to go back, sometimes");
            sassyDesc.setSpan(new StyleSpan(Typeface.ITALIC), sassyDesc.length() - "somtimes".length(), sassyDesc.length(), 0);
            //TapTargetView.showFor(this, TapTarget.forToolbarNavigationIcon(toolbar, "This is the back button", sassyDesc));



            TapTargetView tapTargetView = TapTargetView.showFor(this, TapTarget.forToolbarMenuItem(toolbar, R.id.menuGuardar, "This is a search icon", "As you can see, it has gotten pretty dark around here...")
                            .dimColor(android.R.color.black)
                            .outerCircleColor(R.color.colorAccent)
                            .targetCircleColor(android.R.color.black)
                            .textColor(android.R.color.black)
                            .cancelable(false),
                    new TapTargetView.Listener() {
                        @Override
                        public void onTargetClick(TapTargetView view) {
                            super.onTargetClick(view);
                            view.dismiss(true);
                            toolbar.inflateMenu(R.menu.menu_login);
                        }
                    });
            //TapTargetView.showFor(MainActivity.this,  );

        }catch (Exception ex)
        {
            String error = ex.toString();
        }



        final SwipeRefreshLayout mSwipeRefreshLayout = (SwipeRefreshLayout) findViewById(R.id.coordinatorLayout);




        mSwipeRefreshLayout.setOnRefreshListener(new SwipeRefreshLayout.OnRefreshListener() {
                                                     @Override
                                                     public void onRefresh() {

                                                         SwipeRefreshLayout swipeRefreshLayout = (SwipeRefreshLayout) findViewById(R.id.coordinatorLayout);
                                                         MaterialBetterSpinner materialDesignSpinner = (MaterialBetterSpinner) findViewById(R.id.android_material_design_spinner);
                                                         getUsuarios(materialDesignSpinner, swipeRefreshLayout);

                                                        /* new Timer().schedule(
                                                                 new TimerTask() {
                                                                     @Override
                                                                     public void run() {

                                                                         try {

                                                                             runOnUiThread(new Runnable() {
                                                                                 @Override
                                                                                 public void run() {

                                                                                 }});




                                                                         }catch (Exception ex)
                                                                         {

                                                                         }
                                                                     }
                                                                 },
                                                                 5000
                                                         );*/
                                                     }
                                                 });
        /*realm.executeTransaction(new Realm.Transaction() {
            @Override
            public void execute(Realm realm) {
                Book myDog = realm.createObject(Book.class);
                myDog.setAuthor("Fido2");
                myDog.setId(4);
            }
        });

        try {
            Book myDog = realm.where(Book.class).equalTo("author", "Fidoss").findFirst();

            String d = myDog.getAuthor();
        }catch (Exception ex)
        {
            String e = ex.toString();
        }*/


        //spinner = (MaterialBetterSpinner) findViewById(R.id.android_material_design_spinner);


        spinner.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                spinner.showDropDown();
            }
        });

        spinner.setOnItemClickListener(new AdapterView.OnItemClickListener() {
            @Override
            public void onItemClick(AdapterView<?> adapterView, View view, int position, long l) {
               posUser = position;
                //spinner.showDropDown();
            }
        });

        String[] SPINNERLIST = {"Seleccionar usuario"};

        final ArrayAdapter<String> arrayAdapter = new ArrayAdapter<String>(this,
                android.R.layout.simple_dropdown_item_1line, SPINNERLIST);
        final  MaterialBetterSpinner materialDesignSpinner = (MaterialBetterSpinner)
                findViewById(R.id.android_material_design_spinner);
        materialDesignSpinner.setAdapter(arrayAdapter);

        materialDesignSpinner.setSelection(0);

        getUsuarios(materialDesignSpinner, mSwipeRefreshLayout);
        //  getSupportActionBar().setDisplayHomeAsUpEnabled(true);



        // ATTENTION: This was auto-generated to implement the App Indexing API.
        // See https://g.co/AppIndexing/AndroidStudio for more information.
        client = new GoogleApiClient.Builder(this).addApi(AppIndex.API).build();
    }`

**Comment by xiphirx** [comment]
If you dump the view hierarchy, is there a view underneath the tap target in landscape?

Do you think you can create a small project that shows the problem and share it here?

What device is this running on?

**Comment by ZetDeveloper** [comment]
this is my layout

`<?xml version="1.0" encoding="utf-8"?>
<android.support.v4.widget.SwipeRefreshLayout  xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/coordinatorLayout"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@drawable/gradient_blue"
    tools:context="cn.fanrunqi.materiallogin.MainActivity"
    android:descendantFocusability="beforeDescendants"
    android:focusableInTouchMode="true">

   <RelativeLayout
       android:layout_width="match_parent"
       android:layout_height="match_parent">



    <android.support.v7.widget.Toolbar
        android:id="@+id/toolbar"
        android:layout_width="match_parent"
        android:layout_height="?attr/actionBarSize" >

        <ImageView
            android:layout_height="wrap_content"
            android:layout_width="wrap_content"
            app:logo="@drawable/ic_remove_red_eye_white_24dp"/>

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:weightSum="1">

            <TextView
                android:id="@+id/title"
                android:layout_width="0dp"
                android:layout_height="wrap_content"
                android:layout_weight="1"
                android:text="Eyer"/>



        </LinearLayout>

    </android.support.v7.widget.Toolbar>

    <android.support.v7.widget.CardView
        android:layout_width="300dp"
        android:layout_height="300dp"
        app:cardCornerRadius="0dp"
        app:cardElevation="3dp"
        app:cardUseCompatPadding="true"
        android:layout_centerInParent="true"
        android:id="@+id/cv">
        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:orientation="vertical"
            >
        <RelativeLayout
            android:layout_marginTop="10dp"
            android:layout_width="match_parent"
            android:layout_height="45dp">
            <View
                android:layout_alignParentStart="true"
                android:layout_width="8dp"
                android:layout_height="match_parent"
                android:background="#539fd7"
                />
            <TextView
                android:layout_centerVertical="true"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_marginStart="50dp"
                android:text="@string/login"
                android:textColor="#539fd7"
                android:textSize="22sp"

                />
        </RelativeLayout>
        <LinearLayout
            android:layout_marginTop="10dp"
            android:paddingStart="50dp"
            android:paddingEnd="30dp"
            android:orientation="horizontal"
            android:layout_width="match_parent"
            android:layout_height="55dp">


            <com.weiwangcn.betterspinner.library.material.MaterialBetterSpinner
                android:id="@+id/android_material_design_spinner"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:hint="Seleccione un usuario"

                android:textSize="13sp"
                app:met_hideUnderline="true"
                app:met_baseColor="#539fd7"
                app:met_primaryColor="#539fd7"
                app:met_errorColor="#ddaa00"
                app:met_floatingLabel="none" />

        </LinearLayout>
            <LinearLayout
                android:paddingStart="50dp"
                android:paddingEnd="30dp"
                android:orientation="horizontal"
                android:layout_width="match_parent"
                android:layout_height="50dp">
                <android.support.design.widget.TextInputLayout
                    android:textColorHint="#539fd7"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content">
                    <EditText
                        android:textSize="13sp"
                        android:hint="@string/Password"
                        android:textColor="#539fd7"
                        android:id="@+id/et_password"
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:inputType="textPassword"
                        android:background="@drawable/selector_bg_edit"
                        android:textCursorDrawable="@drawable/bg_input_cursor"
                        android:paddingBottom="2dp"
                        />
                </android.support.design.widget.TextInputLayout>
            </LinearLayout>
            <RelativeLayout
                android:layout_marginTop="25dp"
                android:gravity="center"
                android:layout_width="match_parent"
                android:layout_height="60dp">
                <Button
                    android:id="@+id/bt_go"
                    android:background="@drawable/bt_shape"
                    android:stateListAnimator="@drawable/state_list_animator_z"
                    android:layout_width="150dp"
                    android:layout_height="50dp"
                    android:text="@string/go"
                    android:textColor="#539fd7"
                    android:textAllCaps="false">
                </Button>
            </RelativeLayout>

        </LinearLayout>
        </android.support.v7.widget.CardView>




   </RelativeLayout>
</android.support.v4.widget.SwipeRefreshLayout >`

**Comment by ZetDeveloper** [comment]
this is my layout
[activity_main.txt](https://github.com/KeepSafe/TapTargetView/files/518605/activity_main.txt)

**Comment by xiphirx** [comment]
You're using your toolbar incorrectly. Use `setNavigationIcon` and `setTitle` instead of manually creating views for them. I don't see that this is a problem with the library itself, and I cannot reproduce.

**Comment by ZetDeveloper** [comment]
the attribute android:configChanges in the manifest causes the error, example:

`<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
          package="com.getkeepsafe.taptargetviewsample">

    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:supportsRtl="true"
        android:theme="@style/AppTheme">
        <activity android:name=".MainActivity"  android:configChanges="keyboardHidden|orientation|screenSize|keyboard" >
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>

                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
    </application>

</manifest>`

**Comment by xiphirx** [comment]
Yes, by doing that your activity will not be recreated on rotation, and thus you are not creating a new `TapTargetView` for the landscape layout, which is why its still showing for the old position.

**Comment by ZetDeveloper** [comment]
how can I solve that ?

**Comment by xiphirx** [comment]
Either handle the configuration change yourself or remove `orientation` from `android:configChanges` Either way, this does not happen because of `TapTargetView`
