### ISSUE TITLE
Without target, only text

### ISSUE THREAD

**Issue by Guilherme-HRamos** [KeepSafe/TapTargetView#42]
Hi,
there is a way to don't show target, only a circle background with text? Something like that screenshot about an app that I'm doing?
https://plus.google.com/+GuilhermeHenrique1308/posts/SUERiNBzEFX

Thanks

**Comment by xiphirx** [comment]
Hi. You would need to either target a `TextView` or specify a `Drawable` that renders text as the `icon` to accomplish that look

**Comment by Guilherme-HRamos** [comment]
And about title and subtitle text gravity?

**Comment by xiphirx** [comment]
You cannot modify that currently, and it doesn't seem to align well with Material Design guidelines.

**Comment by Guilherme-HRamos** [comment]
Yes, you are right, but in a bottom|middle circle, it seems good to try a centered text, like the gif in the first post link...

**Comment by xiphirx** [comment]
This library is trying to conform to the Material Design guidelines, sorry.
