### ISSUE TITLE
.cancelable(true) doesn't seem to work

### ISSUE THREAD

**Issue by mumayank** [KeepSafe/TapTargetView#5]

**Comment by xiphirx** [comment]
What are you expecting and what is happening?

**Comment by mumayank** [comment]
I have read the description and according to that I'm expecting `.cancelable(true)` should allow user to click outside the `outerCircle` to dismiss the overlay. That is not happening.

Further, I request you may `.cancelable(true)` dismiss the overlay regardless of where the user has clicked. I believe that would make dismissing overlays friction-less.

**Comment by xiphirx** [comment]
That's odd. Can you share the code you're using to show the tap target and the version of the library you're using? 

In regards to allowing the user to tap anywhere to dismiss: the material design guidelines specifically state that the user must tap outside the outer circle to cancel/dismiss.

**Comment by mumayank** [comment]
Code:
```
new TapTargetView.Builder(HomeActivity.this)
                .title("title")
                .description("")
                .outerCircleColor(R.color.highlight_white)
                .targetCircleColor(R.color.primary)
                .textColor(R.color.text_primary)
                .dimColor(R.color.primary)
                .tintTarget(false)
                .drawShadow(false)
                .cancelable(true) // Whether tapping outside the outer circle dismisses the view
                .showFor(textView);
```

Lib version:
` compile 'com.getkeepsafe.taptargetview:taptargetview:1.0.0'`

Oh, I didn't know these guidelines yet. Thanks for the info :)

**Comment by xiphirx** [comment]
Ah. Please update to version 1.0.1 that should fix your issue

**Comment by mumayank** [comment]
Thanks! Closing this issue 👍
