### ISSUE TITLE
Sequence handling

### ISSUE THREAD

**Issue by mgursch** [KeepSafe/TapTargetView#50]
- [x] I have verified the issue exists on the latest version
- [x] I am able to reproduce it

**Version used:**
1.4.1

Hey 
I need a little bit better handling for the sequence. I have to know what target has been shown last, when the user cancels the sequence

maybe
public void onSequenceCanceled(TapTarget currentTapTarget);

**Comment by xiphirx** [comment]
Sure, sounds good. I don't think there is a good way to identify certain targets, so I also think there should be an assignable ”id” value to each target on creation that can be referenced later

**Comment by mgursch** [comment]
Thanks for the quick implementation - when will it be available?

**Comment by xiphirx** [comment]
You are free to use a snapshot if you need it immediately, there is one other issue open that points to a potential bug that I'd like to address before a new release

**Comment by mgursch** [comment]
Unfortunatelly no new release since today - when will it be released? would prefere to use a stable release not a SNAPSHOT

**Comment by xiphirx** [comment]
1.5.0 is now live
