### ISSUE TITLE
TapTargets for views near the top of the screen show title in status bar

### ISSUE THREAD

**Issue by drampelt** [KeepSafe/TapTargetView#52]
- [x] I have verified the issue exists on the latest version
- [x] I am able to reproduce it

**Version used:** 1.4.1

**Stack trace:** N/A

**Android version:** 7.0

See screenshot. Would it be possible in this case to move the title below the target? I tried setting the bounds manually to a smaller square at the left/right sides of the view but the same thing happened.

![screenshot_20161019-164849](https://cloud.githubusercontent.com/assets/401214/19537102/c177e0d2-961c-11e6-8dc6-6398f8a9cd33.png)

**Comment by xiphirx** [comment]
Hi! Can you share the code you're using to display the tap target?

**Comment by drampelt** [comment]
Thanks for the quick reply! Here is the code I'm using (sorry it's in Kotlin):

```kotlin
                TapTargetView.showFor(
                    activity,
                    TapTarget.forView(name, "Tap here to name your subject!")
                        .outerCircleColor(R.color.blue)
                        .cancelable(false)
                        .dimColor(R.color.black)
                    ,
                    object : TapTargetView.Listener() {
                        override fun onTargetClick(view: TapTargetView?) {
                            super.onTargetClick(view)
                            ...
                        }
                    }
                )
```

**Comment by xiphirx** [comment]
Kotlin is very welcome! Since this is a positioning issue, can you please take a screenshot of the problem with `debug(true)` on the `TapTargetView`? That will show a wire-frame of the various positions each element is taking.

Additionally, can you give the exact location and size of the `name` view on screen? You can do this with `name.getLocationOnScreen(int[])`

**Comment by drampelt** [comment]
Position on screen is `{28, 280}` (on a Nexus 6p so screen dimensions are 2560x1440)

Screenshot with debug mode:

![screenshot_20161019-170539](https://cloud.githubusercontent.com/assets/401214/19537571/7cc49aaa-961e-11e6-9408-3b0439128710.png)

**Comment by drampelt** [comment]
Here's a screenshot using a custom box bound at the left of the view if that helps at all:

![screenshot_2016_10_19_17_10_46](https://cloud.githubusercontent.com/assets/401214/19537746/19489944-961f-11e6-8710-849af36fa10c.png)

**Comment by xiphirx** [comment]
Cool, thanks! I'm going to try to reproduce the problem and subsequently solve it on my end.

**Comment by xiphirx** [comment]
Can you please verify which version of the library you're using again? I cannot reproduce this on my end and I see that the text is drawn over the status bar, which should not be possible in 1.4.1

**Comment by drampelt** [comment]
Definitely using 1.4.1, I do have `android:fitsSystemWindows="true"` in my layout - do you think that could be causing the issue?

**Comment by xiphirx** [comment]
Figured it out. It is because you have `windowTranslucentStatus` set to true in your style + `fitsSystemWindows`. I'll be working on a fix.

**Comment by drampelt** [comment]
Awesome, thanks so much for your help. Loving the library 😄

**Comment by xiphirx** [comment]
I have a fix ready. Please try it out by editing your build to include the following snapshot

`compile 'com.github.KeepSafe:TapTargetView:103b4d5'`

which is hosted on jitpack. You may need to add `maven { url "https://jitpack.io" }` to your repo list

**Comment by drampelt** [comment]
Yes it is working perfectly now. Thank you again for the help!
