### ISSUE TITLE
Target is appearing behind BottomSheetDialog

### ISSUE THREAD

**Issue by k0shk0sh** [KeepSafe/TapTargetView#54]
- [x] I have verified the issue exists on the latest version
- [x] I am able to reproduce it

**Version used:**

**None:**

**Android version: 6.0**

as per the title says, the Target appears behind the BottomSheetDialog even if i used `getActivity()`or `getDialog()`

**Comment by xiphirx** [comment]
Hi, I just tried out sample on a `BottomSheetDialog` and it seems to be working just fine. Please provide some sample code.

Here's the code I ran successfully:

```java
        final BottomSheetDialog sheet = new BottomSheetDialog(this);
        sheet.setContentView(R.layout.dialog_bottom_sheet);
        sheet.setOnShowListener(new DialogInterface.OnShowListener() {
            @Override
            public void onShow(DialogInterface dialog) {
                TapTargetView.showFor(sheet, TapTarget.forView(sheet.findViewById(R.id.droid), "test")
                        .outerCircleColor(R.color.colorPrimary)
                        .tintTarget(false), null);
            }
        });

        sheet.show();
```

**Comment by k0shk0sh** [comment]
my mistake, im using bottomsheet dialogFragment.

**Comment by xiphirx** [comment]
Can you share some code that shows how you're displaying the tap target?

**Comment by xiphirx** [comment]
I have just tested it with a `BottomsheetDialogFragment` and it also works as expected. Please share the code that displays the tap target.

Here's the code I used to test

```java
public class TestBottomSheetDialogFragment extends BottomSheetDialogFragment {
    private BottomSheetBehavior.BottomSheetCallback callback = new BottomSheetBehavior.BottomSheetCallback() {
        @Override
        public void onStateChanged(@NonNull View bottomSheet, int newState) {
            if (newState == BottomSheetBehavior.STATE_EXPANDED) {
                TapTargetView.showFor(getDialog(),
                        TapTarget.forView(getDialog().findViewById(R.id.droid), "Test")
                        .outerCircleColor(R.color.colorPrimary)
                        .tintTarget(false), new TapTargetView.Listener());
            }
        }

        @Override
        public void onSlide(@NonNull View bottomSheet, float slideOffset) {}
    };

    @Override
    public void setupDialog(Dialog dialog, int style) {
        super.setupDialog(dialog, style);
        final View view = View.inflate(getContext(), R.layout.dialog_bottom_sheet, null);
        dialog.setContentView(view);
        final CoordinatorLayout.LayoutParams layoutParams =
                (CoordinatorLayout.LayoutParams) ((View) view.getParent()).getLayoutParams();
        CoordinatorLayout.Behavior behavior = layoutParams.getBehavior();
        if (behavior != null && behavior instanceof BottomSheetBehavior) {
            ((BottomSheetBehavior) behavior).setBottomSheetCallback(callback);
        }
    }
}
```

**Comment by k0shk0sh** [comment]
The only difference is that im showing the TapTarget after the dialog is being showed and not within the onStageChanged, i will definitely try that on Saturday and let you know. you can put this on hold for now. thanks for your help, really appreciate it.

**Comment by k0shk0sh** [comment]
I have tested it out and `if (newState == BottomSheetBehavior.STATE_EXPANDED)` not really applicable when the bottomSheet has a peakHeight for example 250 the state will never called unless if scrolled the `Dialog` myself. what i did is, i'm calling the TargetView on the `Dialog.setOnShowListener` which makes sense. 
Thanks for your help and sorry for the delay.
