### ISSUE TITLE
Close animation unhandled behavior

### ISSUE THREAD

**Issue by IRMobydick** [KeepSafe/TapTargetView#57]
Hi there
I'm using SNAP-SHOT version.
When user touch outside of outer circle, view start close animation.
But if user touch twice and more and more, close animation repeat more and more.

It seems to be a unhandled behavior ;)

**Comment by xiphirx** [comment]
Thanks for the report! Will fix momentarily.

**Comment by IRMobydick** [comment]
Nice job man, but this bug still there when user press back button continuously :D

**Comment by rudistapelfeldt** [comment]
J
