### ISSUE TITLE
Accept Point/ Rect as param for showFor

### ISSUE THREAD

**Issue by mumayank** [KeepSafe/TapTargetView#6]
I'm currently using this library for implementation of feature overlays:
https://github.com/amlcurran/ShowcaseView

This library provides a way to highlight elements by passing Point. That is just great as it helps in highlighting elements which aren't views. Or legacy elements which were not views in earlier android OS versions but have become views in recent versions of android OS. One example I can quote is `ListView`'s `fastScroller` which was a `Drawable` pre-`kitkat`. Post that it became a `view`.

Your lib is already better than this lib. If you add this functionality, your lib will expand to support any area in the app (and not just views) and become even more awesome!

This is just a humble feature request. :)

**Comment by xiphirx** [comment]
Sure. This was in the pipeline anyway :)

I think a rect would suffice.
