### ISSUE TITLE
Problem with transparentTarget=true on Android 4.2

### ISSUE THREAD

**Issue by iTruff** [KeepSafe/TapTargetView#61]
- [true ] I have verified the issue exists on the latest version
- [ true] I am able to reproduce it

Hello.
I have a such problem on device with api 17 (see screenshot)
Can we fix this?

![default](https://cloud.githubusercontent.com/assets/6223322/20177116/c89bfb44-a753-11e6-8042-b0396949c7f8.png)

**Version used:**
compile 'com.getkeepsafe.taptargetview:taptargetview:1.5.1'
**Stack trace:**
No any
**Android version:**
Android Api 17, Nexus 5

**Comment by xiphirx** [comment]
Hi can you share the code you're using to show the tap target?

**Comment by xiphirx** [comment]
I'm closing this due to lack of information. Please comment when you have more information to share.
