### ISSUE TITLE
Description should be optional

### ISSUE THREAD

**Issue by mumayank** [KeepSafe/TapTargetView#7]
Hey, first up, I'm sorry if I'm raising too many issues. I am doing it in a positive way to help give you my honest end-user/ dev experience.

Now on the issue, I haven't read the official guidelines on this matter. If description is mandatory, please close this issue. If not, then I feel not all feature require a description. Title is sufficient. But currently your code will throw an error. Minor issue, but wanted to get clarifications on this, if you may, please?

**Comment by xiphirx** [comment]
Hi, don't worry about reporting issues. I'm glad the library is being used.

The guidelines don't seem to say anything about requiring a title and description. It seems like a reasonable request to me, I'll plan on implementing it.

In the mean time, using an empty string should suffice

**Comment by mumayank** [comment]
Great! Thanks 👍
