### ISSUE TITLE
Can't use android.graphics.Color.rgb()?

### ISSUE THREAD

**Issue by roblav96** [KeepSafe/TapTargetView#70]
I'd like to set the colors programmatically like so:
```java
.outerCircleColor(android.graphics.Color.rgb(255, 0, 0))
```
but it throws `android.content.res.Resources$NotFoundException: Resource ID #0xffff0000`.

Is this really not possible?

**Comment by squarenotch** [comment]
Thank you for such a fantastic library. I would really like to be able to pass a color value rather than ID. Do you think this might be something you might implement?

**Comment by xiphirx** [comment]
Please use 1.5.3 for this functionality.

**Comment by squarenotch** [comment]
@xiphirx Works brilliantly. Thank you very much.

**Comment by roblav96** [comment]
@xiphirx @squarenotch 🌮 🎉 🎂 🎁 🍰
