### ISSUE TITLE
Text not rendering in API 19

### ISSUE THREAD

**Issue by ihhcarus** [KeepSafe/TapTargetView#80]
- [x] I have verified the issue exists on the latest version
- [x] I am able to reproduce it

**Version used:**
1.5.3

**Stack trace:**
No stack trace, but here's how I'm instantiating my tap targets:
```java
new TapTargetSequence(MainActivity.this)
    .targets(
            TapTarget.forToolbarOverflow(toolbar, "Menu", "Use o menu para navegar para outras áreas da app")
                    .tintTarget(false)
                    .transparentTarget(true),
            TapTarget.forView(logo, "De Olho no Futuro", "Aqui você volta para a trilha")
                    .tintTarget(false)
                    .transparentTarget(true)
    )
    .continueOnCancel(true)
    .listener(new TapTargetSequence.Listener() {
        @Override
        public void onSequenceFinish() {}
        @Override
        public void onSequenceCanceled(TapTarget lastTarget) {}
    })
    .start();
```

**Android version:**
4.4.4 (API 19) in Genymotion's Galaxy Note 3 emulator

The tap target's text is not being displayed, here's what I get:
![bugadas](https://cloud.githubusercontent.com/assets/1833584/20685265/df4774fe-b59a-11e6-87e2-49aba45c2379.png)

And here's and example of it displaying correctly, in a device running Lollipop:
![deolhonofuturo-mainactivity-11282016183818](https://cloud.githubusercontent.com/assets/1833584/20685101/1bae70a6-b59a-11e6-87a4-51f7614be059.png)

**Comment by xiphirx** [comment]
That is... interesting. I'm not sure what would be causing this. The library makes use of `StaticLayout`, which is also used in `TextView` AFAIK.

I'll try to reproduce on the genymotion image you specified

**Comment by xiphirx** [comment]
I have downloaded that exact genymotion image, however the text displays properly for me. I'm not sure what else would be causing this issue. 

If you dont mind, can you try to add another genymotion device with the same image and testing on that? It may be a fluke in the image you used.

**Comment by ihhcarus** [comment]
Alright, that's better, glad it showed up normally to you. I might try later again with a fresh image.

Thanks!
