### ISSUE TITLE
[Enhancement] Dismiss TapTargetView on click of navbar back button

### ISSUE THREAD

**Issue by ishaansrm** [KeepSafe/TapTargetView#81]
When user clicks on back button from the navbar, the TapTargetView should be cancelled.
Currently, this happens only when cancelable is set to TRUE.

**Comment by xiphirx** [comment]
`cancelable` is true by default. Hitting back is the same action as canceling, but if you specify that a target is not cancelable, then it shouldn't be canceled by hitting back. If you want the functionality where you can only cancel by hitting back and nothing else, then you'll have to implement that externally.
