### ISSUE TITLE
Target center top of the screen text now shows

### ISSUE THREAD

**Issue by deshan** [KeepSafe/TapTargetView#84]
- [ ] I have verified the issue exists on the latest version

**Version used: just downloaded the latest today**

**Stack trace:**

**Android version: 6.0**

Please see the attached screenshot. I think the text renders above the screen. Is there a way to fix it? 

![screenshot_20160103-120533](https://cloud.githubusercontent.com/assets/234754/20865083/f3fbd10a-ba2d-11e6-81be-5377fed73e55.png)

**Comment by xiphirx** [comment]
Can you share the location of the tap target and the size of your screen? I believe this is related to #80

**Comment by deshan** [comment]
Hmm found the problem.

This line was the issue.

activity class
getWindow().addFlags(WindowManager.LayoutParams.FLAG_LAYOUT_NO_LIMITS);

when comment text positioning correctly.

**Comment by xiphirx** [comment]
Thanks for figuring that out! I'll see what I can do...

**Comment by xiphirx** [comment]
This should be fixed now.

**Comment by deshan** [comment]
Yeah works now. Thanks xiphirx for the quick response.
