### ISSUE TITLE
I added this library and my floatingActionButton class started throwing error while inflating in few devices. This sounds very weird but as soon as i removed the library ,floating action button class started working fine.

### ISSUE THREAD

**Issue by gauravwally** [KeepSafe/TapTargetView#87]
- [ ] I have verified the issue exists on the latest version
- [ ] I am able to reproduce it

**Version used:**

**Stack trace:**

**Android version:**

**Comment by xiphirx** [comment]
I'm going to need more information if you want any chance of this being resolved. Let's start with the stack trace, the code used to display the tap target, the floating action button library used and the Android versions where the problem occurs

**Comment by gauravwally** [comment]
I am using these support design libraries along with taptargetview library. 

compileSdkVersion 23
buildToolsVersion "23.0.3"
compile 'com.android.support:support-v4:23.3.0'
compile 'com.android.support:appcompat-v7:23.2.0'
compile 'com.android.support:design:23.2.0'
compile 'com.getkeepsafe.taptargetview:taptargetview:1.6.0'

Please find logs here.
[Lev.txt](https://github.com/KeepSafe/TapTargetView/files/653882/Lev.txt)

It was working fine on other devices but these  had this crash.
Only change i did was to comment out this library and everything started working smooth for these  devices as well.

1.Lenovo K3 Note, Model:- LenovoK50a40 os:- 5.0
2.Micromax Canvas xpress, Model:- Micromax A99, os:-5.0
3.Htc One M8 Eye, Model:- M8 eye OS:- 5.0.2
4.Samsung Galaxy Note3, Model:- SM-N900 OS:- 5.0

Thanks a lot for your help.

**Comment by xiphirx** [comment]
I need the code you're using to show the tap target. It seems like you're using the same drawable between the fab and the icon of the tap target

**Comment by gauravwally** [comment]
I commented the code for Tap target , after that also i was getting same crash.

However this is the code i used.


  TapTargetView.showFor(getActivity(),                 // `this` is an Activity
                TapTarget.forView(rootView.findViewById(R.id.value), "This is a target", "We have the best targets, believe me")
                        // All options below are optional
                        .outerCircleColor(R.color.reminder_color)
                        .targetCircleColor(R.color.expense_accent) // Specify a color for the outer circle
                        // Specify a color for the target circle
                        .titleTextSize(20)                  // Specify the size (in sp) of the title text
                        .titleTextColor(R.color.white)      // Specify the color of the title text
                        .descriptionTextSize(10)            // Specify the size (in sp) of the description text
                        .descriptionTextColor(R.color.folder_color)  // Specify the color of the description text
                        .textColor(R.color.blue)            // Specify a color for both the title and description text
                        // Specify a typeface for the text
                        .dimColor(R.color.black)            // If set, will dim behind the view with 30% opacity of the given color
                        .drawShadow(true)                   // Whether to draw a drop shadow or not
                        .cancelable(true)                  // Whether tapping outside the outer circle dismisses the view
                        .tintTarget(true)                   // Whether to tint the target view's color
                        .transparentTarget(true)           // Specify whether the target is transparent (displays the content underneath)
                        .icon(getResources().getDrawable(R.drawable.premium_button))                     // Specify a custom drawable to draw as the target
                        .targetRadius(30),                  // Specify the target radius (in dp)
                new TapTargetView.Listener() {          // The listener can listen for regular clicks, long clicks or cancels
                    @Override
                    public void onTargetClick(TapTargetView view) {
                        super.onTargetClick(view);      // This call is optional
                        Toast.makeText(getActivity(), "pop up", Toast.LENGTH_SHORT).show();
                    }
                });

**Comment by xiphirx** [comment]
What icon are you using for the fab?

**Comment by gauravwally** [comment]
This is what i am using for float action button.

<android.support.design.widget.FloatingActionButton xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/float_button"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:layout_alignParentBottom="true"
    android:layout_alignParentRight="true"
    android:layout_margin="8dp"
    android:src="@drawable/camera_fullscreen"
    app:backgroundTint="?attr/colorPrimary"
    app:elevation="6dp"
    app:fabSize="mini"
    app:pressedTranslationZ="12dp" />

I am going to update the library and check again. thanks for your help.

**Comment by xiphirx** [comment]
Seems like you're hitting an Android bug: https://code.google.com/p/android/issues/detail?id=191754

Updating your support library should have fixed it. Since TapTargetView does not make use of a custom drawable class, and we're not calling `mutate` on any drawable, there's nothing the library needs to do.
