### ISSUE TITLE
Custom parent ViewGroup

### ISSUE THREAD

**Issue by leisim** [KeepSafe/TapTargetView#9]
Could you please add a way to set a custom parent `ViewGroup` using the `Builder`?
I want to show the help for a dialog...

**Comment by xiphirx** [comment]
I can see this being useful for navigation drawers, it seems like you're working on getting it in :)

**Comment by xiphirx** [comment]
I have landed my sequence and api changes if you'd like to re-open your PR.

**Comment by rubin-parakhi** [comment]
Could not use TapTargetSequence when using with Gradle. Also TagTargetView in EditText seems unfit

**Comment by xiphirx** [comment]
Please make another issue if you're experiencing a bug with the library.

**Comment by xiphirx** [comment]
#31
