### ISSUE TITLE
Issue displaying in multi window mode

### ISSUE THREAD

**Issue by pyamsoft** [KeepSafe/TapTargetView#91]
- [x] I have verified the issue exists on the latest version
- [x] I am able to reproduce it

**Version used:**
1.6.0

**Stack trace:**

Does not produce a crash, just unexpected behavior.

**Android version:**
7.0

When putting an application into multi window mode and then generating a TapTargetView, the view is displayed incorrectly or sometimes not displayed at all. In most cases, the view is invisible.

This may be due to [this line](https://github.com/KeepSafe/TapTargetView/blob/master/taptargetview/src/main/java/com/getkeepsafe/taptargetview/TapTargetView.java#L143) which decides the root view for the TapTargetView. When in multiwindow mode, the decorView is not always going to be the size of the screen itself as it is usually in a single activity mode.

**Comment by xiphirx** [comment]
Multi-window mode is not currently supported, but it _should_. I'll have to look into how to support it. Please feel free to submit a PR if you have an idea on how to add support.

**Comment by xiphirx** [comment]
I have added a fix for this, will be in the next release.

**Comment by zawadz88** [comment]
Hi @xiphirx,
This does not work on 1.9.1.

Please see the screenshots attached:
![screenshot_1497348039](https://user-images.githubusercontent.com/3322260/27077458-69f458da-5030-11e7-8db9-7ffd03a757aa.png)
![screenshot_1497348057](https://user-images.githubusercontent.com/3322260/27077452-66f4ab76-5030-11e7-9482-c773b5a91b5b.png)

I have a fix in a forked repo (linked in this ticket). Please let me know if you would like me to drop a PR for this.

**Comment by xiphirx** [comment]
Sure if you have a fix I'd be happy to take a look in a PR
