### ISSUE TITLE
When showing a TapTarget after closing a screen that had a keyboard showing, the keyboard leaves a "shadow" above the TapTargetView

### ISSUE THREAD

**Issue by danprado** [KeepSafe/TapTargetView#92]
- [x] I have verified the issue exists on the latest version
- [x] I am able to reproduce it

**Version used:**
1.6.0
**Android version:**
6.0

This seems to happen because when we trigger this lib, it tries to capture the visible window size of the app and if the keyboard hasn't completely disappeared, the lib will consider it is still there.

![pasted image at 2016_12_21 02_24 pm](https://cloud.githubusercontent.com/assets/11525443/21397671/daa37ba2-c78b-11e6-983d-366a7fe26a2a.png)

**Comment by xiphirx** [comment]
Related to #91
