### ISSUE TITLE
Get Error, when using UIAutomator to get element

### ISSUE THREAD

**Issue by BuddyOlx** [KeepSafe/TapTargetView#93]
- [ √ ] I have verified the issue exists on the latest version
- [ √ ] I am able to reproduce it

i get an error from uiautomatorviewer when i try to find out element info from TapTargetView Layout. Can anyone help me?

<img width="884" alt="screen shot 2016-12-22 at 1 53 49 pm" src="https://cloud.githubusercontent.com/assets/19722564/21417611/576f9446-c84e-11e6-9cee-ece810b9c07a.png">

**Comment by xiphirx** [comment]
Dont know, however this isn't an issue with the library.
