### ISSUE TITLE
width and height must be > 0

### ISSUE THREAD

**Issue by heming0512** [KeepSafe/TapTargetView#97]
Version used: 1.5.3

Stack trace:
android.graphics.Bitmap.createBitmap(Bitmap.java:687)
2 android.graphics.Bitmap.createBitmap(Bitmap.java:666)
3 android.graphics.Bitmap.createBitmap(Bitmap.java:633)
4 com.getkeepsafe.taptargetview.ViewTapTarget$1.run(ViewTapTarget.java:47)
5 com.getkeepsafe.taptargetview.ViewUtil$1.onGlobalLayout(ViewUtil.java:60)
6 android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:667)
7 android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2000)
8 android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1139)
9 android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4879)
10 android.view.Choreographer$CallbackRecord.run(Choreographer.java:776)
11 android.view.Choreographer.doCallbacks(Choreographer.java:579)
12 android.view.Choreographer.doFrame(Choreographer.java:548)
13 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:762)

Android version:  4.2.2

wherever i use "TapTarget.forView"on a view,i hava judge this view not null,but sometimes i found
it will throw exception.

**Comment by julioz** [comment]
@heming0512 I think this was already fixed - make sure you're using the latest lib version.

**Comment by xiphirx** [comment]
This has been fixed in the latest version as mentioned previously, please update.
